display draft bids count and submitted bids count
MetaPhase-Consulting/State-TalentMAP pull request #1122
Opened 2020-09-22 20:54 UTC by elizabeth-jimenez

Added an action since the logic needs to be used in more than one component.

2020-09-23 11:30 UTC, mjoyce91 commented on src/actions/bidList.js
> +
I would move this to utilities since it's not really an action

2020-09-23 11:32 UTC, mjoyce91 commented on src/Components/ProfileDashboard/BidList/BidList.jsx
> +  const submittedBids = getBidListStats(bids, 'submitted', true);
Let's import the statuses from `src/Constants/BidData.js`

2020-09-23 11:32 UTC, mjoyce91 commented on src/Components/BidTracker/BidTracker.jsx
> +    const submittedBids = getBidListStats(bidList.results, 'submitted', true);
Let's import the statuses from `src/Constants/BidData.js`

2020-09-23 12:55 UTC, elizabeth-jimenez commented on src/actions/bidList.js
> +
ahh lol, I knew we had a common-helpers kinda files for the FE, just forgot. Will do! Thanks Mike!

2020-09-23 12:56 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/BidList/BidList.jsx
> +  const submittedBids = getBidListStats(bids, 'submitted', true);
oooo, yep!

2020-09-23 14:38 UTC, mjoyce91 commented on src/Components/BidTracker/BidTracker.jsx
> +          Bids submitted:<div className="bid-stat">({submittedBids})</div>
Let's add a space between the colon and the parens

2020-09-23 14:40 UTC, mjoyce91 commented on src/Components/ProfileDashboard/BidList/BidList.jsx
> +  const submittedBids = getBidListStats(bids, SUBMITTED_PROP, true);
You'll need to check multiple props here. A bid can be submitted but not be in the "submitted" phase (ex: in panel, or a CDO viewing it)

![Screen Shot 2020-09-23 at 10 39 17 AM](https://user-images.githubusercontent.com/11576347/94027774-37660080-fd89-11ea-86e0-76610b71fbbf.png)

2020-09-23 14:45 UTC, mjoyce91 commented on src/utilities.js
> +    numBids = padStart((numBids).toString(), 2, '0');
can also use lodash `toString` for better error handling

2020-09-23 14:45 UTC, mjoyce91 commented on src/utilities.js
> +  if (padWithZero) {
what does this do?

2020-09-23 15:22 UTC, elizabeth-jimenez commented on src/utilities.js
> +  if (padWithZero) {
adds a padding of 0 to the front of  numbers < 10, per the designs

2020-09-23 15:23 UTC, elizabeth-jimenez commented on src/utilities.js
> +    numBids = padStart((numBids).toString(), 2, '0');
haha, ok! Will do!

2020-09-23 15:32 UTC, elizabeth-jimenez commented on src/Components/BidTracker/BidTracker.jsx
> +          Bids submitted:<div className="bid-stat">({submittedBids})</div>
woot! 💯

2020-09-23 18:17 UTC, mjoyce91 commented on src/Components/ProfileDashboard/BidList/BidList.jsx
> +  const submittedBids = getBidListStats(bids, SUBMITTED_PROP, true);
Not sure... If a bid becomes unavailable, we probably wouldn't want to include that in either category.

2020-09-23 18:21 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/BidList/BidList.jsx
> +  const submittedBids = getBidListStats(bids, SUBMITTED_PROP, true);
oohh true

2020-09-30 15:38 UTC, mjoyce91 commented
When logged in as Leah, getting 0s

![Screen Shot 2020-09-30 at 11 38 25 AM](https://user-images.githubusercontent.com/11576347/94707502-7e1ba380-0311-11eb-991a-cb11b4d0908c.png)

2020-09-30 15:42 UTC, mjoyce91 requested changes
See screenshot

2020-09-30 16:17 UTC, elizabeth-jimenez commented
> See screenshot

😭

2020-09-30 16:24 UTC, elizabeth-jimenez commented
> When logged in as Leah, getting 0s
> 
> ![Screen Shot 2020-09-30 at 11 38 25 AM](https://user-images.githubusercontent.com/11576347/94707502-7e1ba380-0311-11eb-991a-cb11b4d0908c.png)

🤔 I'm not getting that error for Leah

2020-09-30 16:36 UTC, elizabeth-jimenez commented
@mjoyce91 should be fixed 😅  good find!

2020-10-06 13:43 UTC, mjoyce91 commented on src/Constants/BidData.js
> +  HAND_SHAKE_NEEDS_REGISTER_PROP];
I'm not sure this is always going to be accurate. For example, a `DECLINED` bid is still one that you've submitted. I wonder if we need to call these "Active submitted bids" or something, otherwise we potentially confuse people by thinking they never submitted a certain bid when in reality it was just given to somebody else.

2020-10-06 13:49 UTC, elizabeth-jimenez commented on src/Constants/BidData.js
> +  HAND_SHAKE_NEEDS_REGISTER_PROP];
Yea, true. I wasn't sure if `declined` should be included 🤔

2020-10-09 14:46 UTC, mjoyce91 commented on src/Components/BidTracker/BidTracker.jsx
> +        </div>
Let's move this inside the `isLoading` a couple lines down

2020-10-09 14:47 UTC, mjoyce91 commented on src/Components/ProfileDashboard/BidList/BidList.jsx
> +            </div>
Could we make this a common component since its used here and on the full Bid Tracker screen? Then if we decide to change some verbiage we don't need to do it in both places.

2020-10-09 14:48 UTC, mjoyce91 commented on src/utilities.js
> +
Can we add a few simple tests?

2020-10-13 15:41 UTC, elizabeth-jimenez commented on src/utilities.js
> +
Yep!

2020-10-13 18:37 UTC, mjoyce91 approved these changes

2020-10-13 19:03 UTC, merged