showing date timestamp for HS regsitered
MetaPhase-Consulting/State-TalentMAP pull request #1487
Opened 2021-05-07 16:02 UTC by SidelineCory24

2021-05-07 16:45 UTC, SidelineCory24 commented on src/sass/_bidTracker.scss
> +  opacity: 50%;
updated to 30%

2021-05-07 17:56 UTC, elizabeth-jimenez commented
might also want it for registered status

2021-05-07 18:03 UTC, elizabeth-jimenez commented on src/sass/_bidTracker.scss
> +}
i'd also hide the text on the overlay while on hover

2021-05-07 18:11 UTC, elizabeth-jimenez commented
Oh, make sure the opacity doesn't apply to the action button

2021-05-07 18:49 UTC, mjoyce91 commented
This just seems weird to me from a design/usability perspective. I wonder if we could add some kind of collapse-ability to the overlay, kinda of like the capsule description on the position cards.

![Screen Shot 2021-05-07 at 2 48 09 PM](https://user-images.githubusercontent.com/11576347/117495187-4a59c980-af43-11eb-853a-5e8802704271.png)

2021-05-10 17:12 UTC, SidelineCory24 commented
Still need to setup styling on toggle

2021-05-12 19:55 UTC, elizabeth-jimenez commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +      <div className={`bid-tracker-overlay-alert ${overlayClass} ${showOverlay ? '' : 'abc'}`}>
can actually be `${overlayClass}${showOverlay ? '' : ' abc'}` to save us the space woo

2021-05-13 14:29 UTC, SidelineCory24 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +      <div className={`bid-tracker-overlay-alert ${overlayClass} ${showOverlay ? '' : 'abc'}`}>
done

2021-05-14 18:41 UTC, elizabeth-jimenez commented on src/sass/_bidTracker.scss
> +    margin: 10px 0px -35px 20px;
😍

2021-05-14 18:43 UTC, elizabeth-jimenez commented on src/sass/_bidTracker.scss
> +
🤔 🧼

2021-05-14 18:51 UTC, elizabeth-jimenez commented on src/Components/BidTracker/OverlayAlert/HandshakeRegisterAlert/HandshakeRegisterAlert.jsx
> +
are we still using this?

2021-05-14 18:52 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/BidList/BidList.jsx
> +      showArrow={false}
😻  great job on remembering about the condensed bidtracker

2021-05-14 18:57 UTC, SidelineCory24 commented on src/Components/BidTracker/OverlayAlert/HandshakeRegisterAlert/HandshakeRegisterAlert.jsx
> +
negative 🧼

2021-05-14 19:13 UTC, SidelineCory24 commented on src/sass/_bidTracker.scss
> +
done

2021-05-14 19:14 UTC, SidelineCory24 commented on src/Components/BidTracker/OverlayAlert/HandshakeRegisterAlert/HandshakeRegisterAlert.jsx
> +
done

2021-05-14 19:37 UTC, elizabeth-jimenez commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +        {showArrow && (overlayClass !== CLASS_DRAFT) && (overlayClass !== CLASS_CLOSED) &&
i'd change this to something like: `        {showArrow && includes([HAND_SHAKE_NEEDS_REGISTER_PROP, HAND_SHAKE_ACCEPTED_PROP], get(bid, 'status')) &&
` (dont forget to import `get` and `includes` from lodash) that way if we ever build onto our overlays, we dont have to add another exclusion

2021-05-14 19:41 UTC, elizabeth-jimenez approved these changes
🍰 🥮 🍬 👍 
Looks great and I think it's good to go! Would just like Mike to also give it a look 👀  (at least the ScreenShot)since he recommended the collapsing functionality.

2021-05-14 19:43 UTC, elizabeth-jimenez commented
![image](https://user-images.githubusercontent.com/23065001/118320926-e39c5900-b4ca-11eb-8f92-16f2cc517a0d.png)
SS for @mjoyce91 [linked comment](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1487#pullrequestreview-660150153)

2021-05-14 20:59 UTC, SidelineCory24 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +        {showArrow && (overlayClass !== CLASS_DRAFT) && (overlayClass !== CLASS_CLOSED) &&
done

2021-05-17 13:52 UTC, mjoyce91 commented on src/Components/BidTracker/BidTrackerCard/BidTrackerCard.jsx
> +      unregisterHandshake, showRibbons, showArrow } = this.props;
I'd make the prop name here specific to _functionality_ opposed to specific to the _UI_. For example `isCollapsible`

2021-05-17 13:55 UTC, mjoyce91 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +        {showArrow && includes([HAND_SHAKE_NEEDS_REGISTER_PROP, HAND_SHAKE_ACCEPTED_PROP], get(bid, 'status')) &&
Can we move some of this to a constant above the `return` so that its a bit more readable?

```jsx
const showArrow$ = showArrow && includes([HAND_SHAKE_NEEDS_REGISTER_PROP, HAND_SHAKE_ACCEPTED_PROP], get(bid, 'status'));
```

2021-05-17 13:55 UTC, mjoyce91 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +            </Tooltip>
👍

2021-05-17 13:58 UTC, mjoyce91 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +                name={`arrow-circle-${collapseOverlay ? 'left' : 'right'}`}
Did/can you run this icon by Sarah? Most of our accordions use the chevron so it seems like we'd want to be consistent.

![Screen Shot 2021-05-17 at 9 56 51 AM](https://user-images.githubusercontent.com/11576347/118501080-5e958780-b6f6-11eb-910c-93d796762053.png)

2021-05-17 13:58 UTC, mjoyce91 requested changes
A few pieces of feedback and questions, but overall looks awesome! 💯

2021-05-17 14:08 UTC, mjoyce91 commented
@SidelineCory24 if you want some R A Z Z L E  D A Z Z L E:

```jsx
const rotate = collapseOverlay ? "rotate(180deg)" : "rotate(0)"

  return (
    overlayContent ?
      <div className={`bid-tracker-overlay-alert ${overlayClass}${collapseOverlay ? ' collapse-overlay' : ''}`}>
        {showArrow && includes([HAND_SHAKE_NEEDS_REGISTER_PROP, HAND_SHAKE_ACCEPTED_PROP], get(bid, 'status')) &&
          <InteractiveElement onClick={toggleOverlay}>
            <Tooltip
              title={collapseOverlay ? 'Expand overlay' : 'Collapse overlay'}
              arrow
            >
              <FontAwesome
                style={{ transform: rotate, transition: "all 0.65s linear" }}
                name={`arrow-circle-right`}
              />
```


https://user-images.githubusercontent.com/11576347/118502585-d617e680-b6f7-11eb-91ce-c784aab25176.mov

2021-05-17 14:17 UTC, SidelineCory24 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +                name={`arrow-circle-${collapseOverlay ? 'left' : 'right'}`}
Sarah said she liked the arrow in the circle more. Here's the comparison I sent her:
![image](https://user-images.githubusercontent.com/55964163/118503877-014f0580-b6f9-11eb-9093-e9f2fce20dfe.png)

2021-05-17 14:27 UTC, mjoyce91 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +                name={`arrow-circle-${collapseOverlay ? 'left' : 'right'}`}
Fair enough, thanks!

2021-05-17 14:33 UTC, SidelineCory24 commented on src/Components/BidTracker/BidTrackerCard/BidTrackerCard.jsx
> +      unregisterHandshake, showRibbons, showArrow } = this.props;
done

2021-05-17 14:35 UTC, SidelineCory24 commented on src/Components/BidTracker/OverlayAlert/OverlayAlert.jsx
> +        {showArrow && includes([HAND_SHAKE_NEEDS_REGISTER_PROP, HAND_SHAKE_ACCEPTED_PROP], get(bid, 'status')) &&
done

2021-05-17 14:54 UTC, SidelineCory24 commented
@mjoyce91 requested changes have been made.

2021-05-17 15:22 UTC, mjoyce91 approved these changes

2021-05-17 15:23 UTC, merged