go back to admin dashboard button
MetaPhase-Consulting/State-TalentMAP pull request #1504
Opened 2021-05-14 18:53 UTC by SidelineCory24

2021-05-17 16:29 UTC, SidelineCory24 commented
From a design and usability standpoint I think it makes sense to only have the button show on the Glossary and About pages. After using the edit button you can still use the browsers back arrow to go to the "Editable Content Areas" Page.

2021-05-17 17:02 UTC, mjoyce91 commented on src/Components/HomePageBanner/HomePageBanner.jsx
> +          <BackButton />
Even without the line break issue, it seems weird including this button here

![Screen Shot 2021-05-17 at 1 01 27 PM](https://user-images.githubusercontent.com/11576347/118528201-0ff4e700-b710-11eb-9734-03b8554fd438.png)

2021-05-17 17:02 UTC, mjoyce91 commented on src/Components/HomePageBanner/HomePageBanner.jsx
> +          <BackButton />
If you could do it in a way that didn't affect the vertical spacing of the TalentMAP logo, then I might be OK with it

2021-05-17 17:02 UTC, mjoyce91 requested changes
Homepage

2021-05-17 17:16 UTC, mjoyce91 commented on src/Components/ResultsSearchHeader/ResultsSearchHeader.jsx
> +          <BackButton />
This also just looks weird

![Screen Shot 2021-05-17 at 1 15 46 PM](https://user-images.githubusercontent.com/11576347/118529891-03718e00-b712-11eb-9d88-3053336f4620.png)

2021-05-17 20:25 UTC, elizabeth-jimenez commented on src/Components/ResultsSearchHeader/ResultsSearchHeader.jsx
> +          <BackButton />
I agree with Mike and I feel like you felt like the buttons looked weird too, Cory 😅 Cory had a good point earlier: this ticket is super old. So maybe we want to run it by chris and robin and see if they even still want this (especially since we could just use..... the browser back button.... gasp!)

The SSs in this PR will be helpful since there were no designs for the ticket (Cory you can bring it up tomorrow, either at Prasanna's weekly status or at grooming session)

🔙

2021-05-18 13:53 UTC, SidelineCory24 commented on src/Components/HomePageBanner/HomePageBanner.jsx
> +          <BackButton />
![image](https://user-images.githubusercontent.com/55964163/118663625-d62ee980-b7be-11eb-9ba1-d4cff25917cf.png)

2021-05-18 13:53 UTC, SidelineCory24 commented on src/Components/HomePageBanner/HomePageBanner.jsx
> +          <BackButton />
🤷‍♂️

2021-05-18 19:37 UTC, SidelineCory24 commented
Closing. Team agreed this was not need. Will put the ticket at the bottom of the backlog jic.

2021-05-18 19:42 UTC, closed without merging