collapsing overlay on different resolutions
MetaPhase-Consulting/State-TalentMAP pull request #1623
Opened 2021-07-12 15:48 UTC by SidelineCory24

This was not originally collapsing
![image](https://user-images.githubusercontent.com/55964163/125317464-04d0c880-e307-11eb-92e5-eb4487eb38fc.png)

2021-07-12 18:35 UTC, elizabeth-jimenez commented
This works, but im having to click on the very edge of the arrow in order to activate the collapse. It hides behind the pink(added to visualize issue):
![image](https://user-images.githubusercontent.com/23065001/125338577-605a8080-e31e-11eb-8a81-a3acf09da9c1.png)

2021-07-12 18:42 UTC, elizabeth-jimenez commented
> This works, but im having to click on the very edge of the arrow in order to activate the collapse. It hides behind the pink(added to visualize issue):
> ![image](https://user-images.githubusercontent.com/23065001/125338577-605a8080-e31e-11eb-8a81-a3acf09da9c1.png)

Adding a `margin-top: 35px` to `.bid-tracker-overlay-alert-content` and a `top: 0` to `bid-tracker-alert-container--register` should fix it, but make sure to check all the edges cases (lots with bidtracker)

2021-07-16 19:49 UTC, mjoyce91 commented on src/sass/_bidTracker.scss
> +  // top: 35px;
comment needed?

2021-07-19 12:49 UTC, mjoyce91 commented on src/sass/_bidTracker.scss
>  .bid-tracker-alert-container--register {
![Screen Shot 2021-07-19 at 8 48 19 AM](https://user-images.githubusercontent.com/11576347/126162147-267d1200-0935-4f71-9d2f-becf93a81a40.png)

2021-07-19 12:50 UTC, mjoyce91 requested changes
Take a look at the mini bid tracker screenshot

2021-07-19 14:12 UTC, SidelineCory24 commented on src/sass/_bidTracker.scss
> +  // top: 35px;
removed

2021-07-19 20:06 UTC, SidelineCory24 commented on src/sass/_bidTracker.scss
>  .bid-tracker-alert-container--register {
update made

2021-07-19 20:15 UTC, SidelineCory24 commented
disregard last push, still broken

2021-07-21 20:31 UTC, elizabeth-jimenez approved these changes
🍰 🍬 🧁 👍

2021-07-23 14:42 UTC, SidelineCory24 commented
@mjoyce91 I think you may be the only one who can approve this due to the change request 😅

2021-07-23 15:05 UTC, mjoyce91 approved these changes

2021-07-23 17:23 UTC, merged