agenda item history route
MetaPhase-Consulting/State-TalentMAP pull request #1839
Opened 2021-11-15 19:22 UTC by SidelineCory24

Adding the basic functionality of clicking `View History` and being routed to the `Employee Agenda Item History` page with the `Go Back` button

2021-11-15 21:07 UTC, SidelineCory24 commented on src/Constants/Menu.js
> +          icon: 'user-circle-o',
I could not find the icon in the design.

2021-11-16 14:15 UTC, mjoyce91 commented
@SidelineCory24 - I think what I would do here is still add the Container and some of the basic styling that's found elsewhere (CDO Portfolio would be a good route to reference). I think what you could is copy `Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx` and `Containers/BidderPortfolio/BidderPortfolio.jsx` and just strip out all the unnecessary logic.

2021-11-16 20:19 UTC, SidelineCory24 commented
> @SidelineCory24 - I think what I would do here is still add the Container and some of the basic styling that's found elsewhere (CDO Portfolio would be a good route to reference). I think what you could is copy `Components/BidderPortfolio/BidderPortfolioPage/BidderPortfolioPage.jsx` and `Containers/BidderPortfolio/BidderPortfolio.jsx` and just strip out all the unnecessary logic.

I've added the suggested/strip styling. Let me know if this was the right idea.

2021-11-17 15:35 UTC, mjoyce91 commented on src/Constants/Menu.js
> +      checkFlag('flags.agenda_search') ?
We'll need to either change the name or increase the width of the menu. My recommendation would be changing to "Employee Agendas"

https://user-images.githubusercontent.com/11576347/142231205-b9f225fa-7533-41b1-8020-100e08380066.mov

2021-11-17 15:38 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +  return (
Somewhere in here you'll want to use the `.profile-content-inner-container` class. Notice the difference in padding between the title and the borders:

![Screen Shot 2021-11-17 at 10 36 48 AM](https://user-images.githubusercontent.com/11576347/142231575-2de4e48c-eae0-45d7-9031-a08d1e7a5d76.png)

![Screen Shot 2021-11-17 at 10 36 41 AM](https://user-images.githubusercontent.com/11576347/142231576-47eb15d8-79bd-4d6a-a6da-95c3e7fe0201.png)

2021-11-17 15:42 UTC, mjoyce91 commented on src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
> +  const [viewType, setViewType] = useState('true');
should be `true` not `'true'`

2021-11-17 15:43 UTC, mjoyce91 commented on src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
> +              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
Can we move this to a class? May want to create a new .scss file

2021-11-17 15:44 UTC, mjoyce91 commented on src/Components/CdoPage/CdoPage.jsx
> +      <Route path="/profile/cdo/agendaitemhistory/perdet" render={() => <AgendaItemHistory />} />
Should be `:perdet` instead of `perdet`

2021-11-17 15:45 UTC, mjoyce91 commented on src/Components/CdoPage/CdoPage.jsx
> +      <Route path="/profile/cdo/agendaitemhistory/perdet" render={() => <AgendaItemHistory />} />
I think I'd also just call it `:id` since that's the naming we usually use

2021-11-17 15:46 UTC, SidelineCory24 commented on src/Constants/Menu.js
> +      checkFlag('flags.agenda_search') ?
update to `Employee Agendas`

2021-11-17 15:46 UTC, mjoyce91 commented
Should just need to re-run snapshots 📸 

![Screen Shot 2021-11-17 at 10 46 24 AM](https://user-images.githubusercontent.com/11576347/142233188-108e28f4-3949-4159-87d9-27d08966570f.png)

2021-11-17 15:47 UTC, mjoyce91 requested changes
Looks good for the most part, just some style tweaks and a few small things and should be good to go

2021-11-17 16:34 UTC, SidelineCory24 commented on src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
> +  const [viewType, setViewType] = useState('true');
done

2021-11-17 16:40 UTC, SidelineCory24 commented on src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
> +              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
done

2021-11-17 16:45 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +  return (
done

2021-11-17 17:41 UTC, SidelineCory24 commented
> Looks good for the most part, just some style tweaks and a few small things and should be good to go

should be gtg now

2021-11-18 20:51 UTC, mjoyce91 commented
We want the title but not the search bar to be padded. Note the difference between these two. Maybe just flip the title and the search bar to match?

![Screen Shot 2021-11-18 at 3 50 08 PM](https://user-images.githubusercontent.com/11576347/142494579-222a3cb9-fba3-48b5-b5a9-22a416f84ca4.png)
![Screen Shot 2021-11-18 at 3 50 03 PM](https://user-images.githubusercontent.com/11576347/142494581-27593b33-7e2e-49de-9662-7ead361b151a.png)

2021-11-18 21:26 UTC, SidelineCory24 commented on src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
> +                <ExportLink disabled />
Hey Mike, I have the other ticket that works on this styling. Should I add it all on this branch or create another branch for that particular ticket?

2021-11-19 13:36 UTC, mjoyce91 commented on src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
> +                <ExportLink disabled />
Oh got it, yeah can do it in the other ticket

2021-11-19 13:38 UTC, mjoyce91 commented on src/Components/Agenda/AgendaItemHistory/AgendaItemHistory.jsx
> +                <button className="create-item-button" onClick={() => createItem()}>Create</button>
When you have a function call that doesn't pass any parameters, you can just call it like this:

```jsx
onClick={createItem}
```

2021-11-19 13:41 UTC, mjoyce91 commented
Looks good, just the comment on the function call and then I'll approve

2021-11-19 13:46 UTC, SidelineCory24 commented
> Looks good, just the comment on the function call and then I'll approve

Update has been made for the function

2021-11-19 16:21 UTC, mjoyce91 approved these changes

2021-11-19 17:26 UTC, merged