employee agenda search cards TM-2400
MetaPhase-Consulting/State-TalentMAP pull request #1857
Opened 2021-11-29 23:10 UTC by SidelineCory24

2021-11-29 23:12 UTC, SidelineCory24 commented
If there are better FA icons let me know

2021-12-07 17:10 UTC, elizabeth-jimenez commented
![image](https://user-images.githubusercontent.com/23065001/145074504-7318cf3a-ef53-48b4-b3ce-47c6484bccaa.png)
Can we add some media queries for smaller screens? AT about 1400, it starts to look like this, but there is still a lot of space there so it should still be able to maintain the same format (with these inputs anyways).

Also, let's vertically center the initials circle

2021-12-07 17:29 UTC, elizabeth-jimenez commented
![image](https://user-images.githubusercontent.com/23065001/145077096-9eec8c33-af57-496d-94dc-c955c332729d.png)
Can we align the icons with the text? I think the Designs had the author name in bold, but it looks strange - let's go ahead and unbold it

2021-12-07 17:32 UTC, elizabeth-jimenez commented
little to no blur on the box-shadow
![image](https://user-images.githubusercontent.com/23065001/145077896-39cdb4e9-b6c0-41d2-a69c-84ac1c9555fd.png)

![image](https://user-images.githubusercontent.com/23065001/145077806-383807c1-bcdd-47f3-b5d2-d929ad5df80f.png)
can we add the same box-shadow from the card to the row?

2021-12-07 17:33 UTC, elizabeth-jimenez commented
I think we still want author in the row view
![image](https://user-images.githubusercontent.com/23065001/145078174-09d96b36-23df-4a49-acb1-cfd769ed925b.png)

2021-12-07 17:38 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +  const useCDOBidding = () => checkFlag('flags.cdo_bidding');
?

2021-12-07 17:39 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +import PropTypes from 'prop-types';
I would change the name of this file to be singular since it it rendering a single card

2021-12-07 17:41 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +          <div className="employee-agenda-row">
I would make sure these css classes "match". Either change "employee-agenda-row" to "employee-agenda-row-list" or change "employee-agenda-card-list" to "employee-agenda-card"

2021-12-07 17:44 UTC, elizabeth-jimenez commented on src/sass/_agenda.scss
> +  div:nth-of-type(2) { flex: 2; }
these don't seem to do anything

2021-12-07 17:45 UTC, elizabeth-jimenez commented on src/sass/_agenda.scss
> +  .create-pai-box-button {
i'd call these `ai` instead of `pai`

2021-12-07 17:48 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
> +  results: BIDDER_OBJECT.isRequired,
can we change to 'result'? Not a big deal, but could make it easier during integration to know that a single result is expected here

2021-12-07 18:17 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +            </InteractiveElement>
Let's just use actual `button`s for all of these. We look some of the common look and feel / button highlighting colors when we use the InteractiveElement and the custom class

2021-12-07 18:18 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
> +            <dt>ORG:</dt>
Can be lowercase `Org:`

2021-12-07 18:18 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
> +            <FA name="building-o" />
Icons here are a bit unaligned compared to the text
![Screen Shot 2021-12-07 at 1 18 23 PM](https://user-images.githubusercontent.com/11576347/145084532-e832a795-f931-4609-b26a-8fd63843bc90.png)

2021-12-07 18:22 UTC, mjoyce91 commented
Noticing a couple things here
- Quite a bit of left padding
- The padding seems to be percent-based which causes the rows to actually move left as the browser width is decreased

https://user-images.githubusercontent.com/11576347/145084945-39e36e37-3bcb-49f4-a890-2c2f488523ae.mov

2021-12-07 18:29 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +      </button>
Can we use the icons that we use elsewhere? This might actually be a common component

![Screen Shot 2021-12-07 at 1 29 10 PM](https://user-images.githubusercontent.com/11576347/145085921-d8e27770-fafd-4bb7-bce7-264e604d4fad.png)

2021-12-07 18:29 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +            ))}
Let's add a TODO to include React keys once we have real data

2021-12-07 18:31 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +              <Link to="/profile/public/4">{results.bidder}</Link>
I think this is fine

2021-12-07 18:36 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +            </InteractiveElement>
Can also use the `LinkButton` component that we have

2021-12-07 18:41 UTC, mjoyce91 commented
Take a look at failing tests - mostly snapshots and missing props

https://app.circleci.com/pipelines/github/MetaPhase-Consulting/State-TalentMAP/8929/workflows/74efe14d-3215-4a31-b55f-c26820b01039/jobs/33874

2021-12-07 20:00 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
> +            <dt>ORG:</dt>
done

2021-12-07 20:00 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
> +            <FA name="building-o" />
done

2021-12-07 20:01 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +      </button>
this is functionality is on another ticket

2021-12-07 20:02 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +            ))}
done

2021-12-07 20:04 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
> +  results: BIDDER_OBJECT.isRequired,
done

2021-12-07 20:04 UTC, SidelineCory24 commented on src/sass/_agenda.scss
> +  .create-pai-box-button {
done

2021-12-07 20:05 UTC, SidelineCory24 commented on src/sass/_agenda.scss
> +  div:nth-of-type(2) { flex: 2; }
done

2021-12-07 20:13 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +          <div className="employee-agenda-row">
removed "list" and updated naming where needed

2021-12-07 20:17 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +  const useCDOBidding = () => checkFlag('flags.cdo_bidding');
was using `showHandshakeIcon` for the dummy data so every card didn't have the hs icon

2021-12-07 20:26 UTC, SidelineCory24 commented
> I think we still want author in the row view ![image](https://user-images.githubusercontent.com/23065001/145078174-09d96b36-23df-4a49-acb1-cfd769ed925b.png)

Author has been added

2021-12-07 21:02 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +import PropTypes from 'prop-types';
done

2021-12-07 21:36 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchRow/EmployeeAgendaSearchRow.jsx
> +  // does Handshake Status need to be added below?
nah

2021-12-07 21:57 UTC, SidelineCory24 commented
> little to no blur on the box-shadow ![image](https://user-images.githubusercontent.com/23065001/145077896-39cdb4e9-b6c0-41d2-a69c-84ac1c9555fd.png)
> 
> ![image](https://user-images.githubusercontent.com/23065001/145077806-383807c1-bcdd-47f3-b5d2-d929ad5df80f.png) can we add the same box-shadow from the card to the row?

using the card box-shadow now

2021-12-07 22:45 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
> +        </div>}
i'd limit the flag coverage to just the Create Agenda Item - although we'll probably create another one to capture the whole thing during integration - maybe also leave a reminder comment to update the flag to a new one

2021-12-07 22:47 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
> +import { Handshake } from '../../Ribbon';
`Components/Ribbon`

2021-12-07 22:48 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
> +import InteractiveElement from '../../InteractiveElement';
`Components/InteractiveElement`

2021-12-07 22:51 UTC, elizabeth-jimenez commented on src/sass/_agenda.scss
> +  flex-grow: 100;
needed?

2021-12-07 22:52 UTC, elizabeth-jimenez commented on src/sass/_agenda.scss
> +  list-style: none;
needed?

2021-12-08 13:08 UTC, SidelineCory24 commented on src/sass/_agenda.scss
> +  flex-grow: 100;
removed

2021-12-08 13:08 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
> +import InteractiveElement from '../../InteractiveElement';
updated

2021-12-08 13:08 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
> +import { Handshake } from '../../Ribbon';
updated

2021-12-08 13:09 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchCard/EmployeeAgendaSearchCard.jsx
> +        </div>}
flag coverage updated and added a comment to update the flag during integration

2021-12-08 13:10 UTC, SidelineCory24 commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +            </InteractiveElement>
`LinkButton` is being used for both `View History` and `Create Agenda Item` buttons now

2021-12-08 13:12 UTC, SidelineCory24 commented on src/sass/_agenda.scss
> +  list-style: none;
removed `list-style`, flexes are needed

2021-12-08 13:13 UTC, SidelineCory24 commented
> Take a look at failing tests - mostly snapshots and missing props
> 
> https://app.circleci.com/pipelines/github/MetaPhase-Consulting/State-TalentMAP/8929/workflows/74efe14d-3215-4a31-b55f-c26820b01039/jobs/33874

test/snaps are passing now

2021-12-08 13:18 UTC, SidelineCory24 commented
> Noticing a couple things here
> 
> * Quite a bit of left padding
> * The padding seems to be percent-based which causes the rows to actually move left as the browser width is decreased
> 
>  Screen.Recording.2021-12-07.at.1.20.17.PM.mov

Shifting fixed @mjoyce91

https://user-images.githubusercontent.com/55964163/145215031-477fe24c-4374-4575-a4c4-d1c8fb9d3912.mp4

2021-12-08 13:42 UTC, mjoyce91 commented on src/Components/Agenda/EmployeeAgendaSearch/EmployeeAgendaSearch.jsx
> +      </button>
Got it!

2021-12-08 14:01 UTC, mjoyce91 commented
v nice

![Screen Shot 2021-12-08 at 9 01 50 AM](https://user-images.githubusercontent.com/11576347/145221288-75f31c2e-a17c-4702-ad30-f829e09b9e6f.png)

2021-12-08 14:10 UTC, mjoyce91 commented
Can we reduce the margin-left here?

Current:
![Screen Shot 2021-12-08 at 9 08 47 AM](https://user-images.githubusercontent.com/11576347/145222383-ad104a0b-2139-43b2-b3fe-1a3eb2d2a0d1.png)

`margin-left: 0`
![Screen Shot 2021-12-08 at 9 09 58 AM](https://user-images.githubusercontent.com/11576347/145222518-23a197bf-dedf-41ef-944d-72d04877aeca.png)

2021-12-08 14:13 UTC, mjoyce91 commented
I think this would look better if we dropped the `font-weight: bold` and reduced font-size to 37px

before
![Screen Shot 2021-12-08 at 9 11 58 AM](https://user-images.githubusercontent.com/11576347/145222926-3ce3836b-231d-4b93-90aa-870835a9d54a.png)

after
![Screen Shot 2021-12-08 at 9 11 44 AM](https://user-images.githubusercontent.com/11576347/145222908-31ec6a1c-bffb-4fbe-bb39-22cc61d545d2.png)

2021-12-08 14:32 UTC, SidelineCory24 commented
@mjoyce91 the circle text and row view margin adjustments have been made.

2021-12-08 14:46 UTC, elizabeth-jimenez commented
![image](https://user-images.githubusercontent.com/23065001/145227594-9686c313-d240-477a-9a8a-0168f2d8fee1.png)
the icons on the row view aren't aligned. I saw that for the cards you added a static padding to align them - instead, for both, just add `align-items: center` to `employee-agenda-row-data-point` (for the row) and remove any top and bottom padding on the icon itself - this will help them stay aligned at different screen resolutions

2021-12-08 14:47 UTC, elizabeth-jimenez commented
@SidelineCory24 https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/1857#issuecomment-988116353 still needs to be done

2021-12-08 15:03 UTC, elizabeth-jimenez commented on src/sass/_agenda.scss
> +        padding: 0 6px 0 0;
You can just do `padding-left`

2021-12-08 15:04 UTC, SidelineCory24 commented on src/sass/_agenda.scss
> +        padding: 0 6px 0 0;
😅

2021-12-08 15:31 UTC, elizabeth-jimenez commented on src/Components/Agenda/EmployeeAgendaSearchCards/EmployeeAgendaSearchCards.jsx
> +  const useCDOBidding = () => checkFlag('flags.cdo_bidding');
I meant the flag, which we already fixed by adding a comment to update it during integration 😅

2021-12-08 15:34 UTC, mjoyce91 approved these changes

2021-12-08 15:36 UTC, elizabeth-jimenez requested changes
Media query comment

2021-12-08 15:37 UTC, SidelineCory24 commented
> Media query comment

Update has been made.

2021-12-08 16:39 UTC, elizabeth-jimenez approved these changes
🦜 looks very nice!

2021-12-08 17:02 UTC, merged