Chore/changelog 2
MetaPhase-Consulting/State-TalentMAP pull request #2018
Opened 2022-03-18 19:36 UTC by mjoyce91

2022-03-18 20:25 UTC, elizabeth-jimenez commented on .github/workflows/size-label.yml
> +              "0": "XS",
I like these sizes lol - i went through some of my old PRs and was like guessed at the size before looking at the lines

2022-03-18 20:26 UTC, elizabeth-jimenez commented on .github/workflows/pr-review.yml
> +        REMOVE_LABEL: "awaiting%20review"
i just dont see the awaiting review label that we are asking to be removed

2022-03-18 20:26 UTC, elizabeth-jimenez requested changes
testing

2022-03-18 20:28 UTC, elizabeth-jimenez approved these changes

2022-03-19 14:42 UTC, mjoyce91 commented on .github/workflows/pr-review.yml
> +        REMOVE_LABEL: "awaiting%20review"
Perhaps we're supposed to add that ourselves?

2022-03-19 14:43 UTC, merged