Fix/aim styling refactor
MetaPhase-Consulting/State-TalentMAP pull request #2336
Opened 2022-09-26 18:56 UTC by SidelineCory24

2022-09-26 20:52 UTC, SidelineCory24 commented
Before changes
https://user-images.githubusercontent.com/55964163/192377700-84f60e3e-ca1f-476c-9230-3d9708429d63.mp4

After changes

Uploading resizing-aim5.mp4…

2022-09-26 21:09 UTC, SidelineCory24 commented
After changes
Uploading resizing-aim5.mp4…

2022-09-27 16:28 UTC, elizabeth-jimenez commented on src/sass/_agendaItemMaintenance.scss
> +    }
Nice catch!

2022-09-27 16:37 UTC, elizabeth-jimenez commented on src/sass/_agendaItemMaintenance.scss
> +    padding-bottom: 20px;
we can remove this - might look a bit better with no padding. See how the scroll seems to dangle lol
![image](https://user-images.githubusercontent.com/23065001/192584998-c61c4e14-2e3a-4fea-8297-59c259b5247d.png)

2022-09-27 17:09 UTC, elizabeth-jimenez requested changes
Looks great! Just a few changes

2022-09-27 17:56 UTC, SidelineCory24 commented on src/sass/_agendaItemMaintenance.scss
> +    padding-bottom: 20px;
done

2022-09-27 17:58 UTC, SidelineCory24 commented on src/sass/_agendaItemMaintenance.scss
> +    }
yeah it does and keeps it consistent with the stacked view.

2022-09-27 17:59 UTC, SidelineCory24 commented
> Looks great! Just a few changes

feedback has been addressed

2022-09-27 18:26 UTC, elizabeth-jimenez commented on src/sass/_agendaItemMaintenance.scss
> -    margin-left: 20px;
You can remove it from below now too, cause 0 and nothing seem to be the same

2022-09-27 18:29 UTC, elizabeth-jimenez approved these changes
🐈

2022-09-27 18:34 UTC, SidelineCory24 commented on src/sass/_agendaItemMaintenance.scss
> -    margin-left: 20px;
done

2022-09-27 20:04 UTC, merged