PMA - Filters TM-4138
MetaPhase-Consulting/State-TalentMAP pull request #2484
Opened 2023-03-08 22:20 UTC by scott062

2023-03-08 22:25 UTC, scott062 commented
Still waiting to figure out how the org filter will work - will probably require mock and api PRs

2023-03-13 12:50 UTC, elizabeth-jimenez commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +  const { data: orgs, loading: orgsLoading } = useDataLoader(api().get, '/fsbid/agenda_employees/reference/current-organizations/');
🦜

2023-03-13 12:50 UTC, elizabeth-jimenez commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +    const grades$ = selectedGrades.flatMap(({ code }) => ([
;)

2023-03-13 14:10 UTC, elizabeth-jimenez commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +        { 'legs.pos_num': `^${t}` },
what was the motivation behind this?

2023-03-13 14:14 UTC, scott062 commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +        { 'legs.pos_num': `^${t}` },
Before I was doing includes - ex.
Target: #123456789
Match: #6789
-
Now its start with - ex.
Target: #123456789
Match: #123
- 
Basically nobody should be typing in only the last part of the num - they should start with the identical beginning match and if they haven't finished typing then it'll still match and give them hints at where to keep going

2023-03-13 14:14 UTC, elizabeth-jimenez commented
I'm wondering if we should remove the Search button? Since the searching is Live? Not done checking, so this could be for an edge-case i'm just not seeing yet

2023-03-13 14:16 UTC, elizabeth-jimenez commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +        { 'legs.pos_num': `^${t}` },
"nobody should be typing in only the last part of the num" that makes complete sense!

2023-03-13 14:27 UTC, elizabeth-jimenez commented
Seeing some weird behavior with the Remarks dropdown - when i go down the list and select for the other dropdowns, it is smooth, but not for Remarks. Hard to explain, so lemme know if you see it. Just go down and start selecting them one by one.

2023-03-13 14:28 UTC, elizabeth-jimenez commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +              placeHolder="Search for Agenda using Position, Name, or Official Item #"
❤️

2023-03-13 15:14 UTC, elizabeth-jimenez commented
![image](https://user-images.githubusercontent.com/23065001/224744351-e221bd01-ac47-4615-9b49-1b52e1356919.png)
should we standardize by adding Item to Category and removing it from Action?

2023-03-13 15:17 UTC, scott062 commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
>          { 'updaters.emp_user.emp_user_last_name': t },
Non emp vs emp I believe unless our mapping is consistent

2023-03-13 15:21 UTC, scott062 commented
> I'm wondering if we should remove the Search button? Since the searching is Live? Not done checking, so this could be for an edge-case i'm just not seeing yet

We shouldn't be using it probably - should I remove it?

2023-03-13 15:22 UTC, elizabeth-jimenez commented
> > I'm wondering if we should remove the Search button? Since the searching is Live? Not done checking, so this could be for an edge-case i'm just not seeing yet
> 
> We shouldn't be using it probably - should I remove it?

Yea! 💪

2023-03-13 15:22 UTC, elizabeth-jimenez commented
> > ![image](https://user-images.githubusercontent.com/23065001/224744351-e221bd01-ac47-4615-9b49-1b52e1356919.png) should we standardize by adding Item to Category and removing it from Action?
> 
> Or do we want to remove `Item` from everywhere?

That works!

2023-03-13 15:23 UTC, elizabeth-jimenez commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
>          { 'updaters.emp_user.emp_user_last_name': t },
ahhhh gotcha!

2023-03-13 15:42 UTC, elizabeth-jimenez commented
Free Text: 
- [x] Position Num look up starts with (and works for positions that start with a 0)
- [x] Position name
- [x] Creator
- [x] Updater
- [x] Bidder
- [x] CDO
- [x] Official item num

- [x] Bureau (not seeing all in dropdown, but the ones that are do filter properly) (current assignment)
- [x] Org (only for position)
- [x] Category
- [x] Grade - filters on person grade
- [x] Grade - filters on position grade
- [x] Action
- [x] Status
- [x] Language - filters on person
- [x] Language - filters on position
- [ ] Remarks (seeing some weird behavior with the dropdown, but the filtering is g2g)
- [x] Skill - just person


- [x] Or within filters And between them

2023-03-13 15:49 UTC, elizabeth-jimenez requested changes
Just a few small changes

2023-03-13 15:52 UTC, elizabeth-jimenez commented
I really like this fuse search - it is SO fast; great job Scott!

2023-03-13 16:35 UTC, scott062 commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +                  valueKey="seq_num"
Fixes dropdown bug

2023-03-13 16:47 UTC, elizabeth-jimenez commented on src/Components/Panel/PanelMeetingAgendas/PanelMeetingAgendas.jsx
> +              noButton
nah, this is fine!

2023-03-13 16:50 UTC, elizabeth-jimenez approved these changes
🐈‍⬛

2023-03-13 16:51 UTC, merged