WIP - remove payload data for Bureau user
MetaPhase-Consulting/State-TalentMAP pull request #2595
Opened 2023-06-27 20:28 UTC by elizabeth-jimenez

Dual Merge: 
- [API PR](linkToAPIPR)

[Ticket TM-4423](https://metaphase.atlassian.net/browse/TM-4423)

2023-06-27 20:28 UTC, elizabeth-jimenez commented on src/actions/userProfilePublic.js
> +  console.log('🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳');
🥳

2023-06-27 20:29 UTC, elizabeth-jimenez commented on src/Containers/ProfilePublic/ProfilePublic.jsx
> +  const isBureau = get(ownProps, 'match.params.viewType') === 'bureau';
Tracer code for now

2023-06-27 20:29 UTC, elizabeth-jimenez commented on src/actions/userProfilePublic.js
> +        // Option 1: api remains consistent for all users and we remove here on FE
1️⃣

2023-06-28 15:22 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
> +        : emp_profile_urls?.external) || emp_profile_urls?.externalRedacted;
May update based on decided approach, but for now the idea is:
If redacted is specified, then we go with that one. We fall back to redacted, cause some profiles won't even be exposed to unredacted.

2023-07-04 21:52 UTC, M00staff commented on src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
> -import { get } from 'lodash';
👍

2023-07-04 22:30 UTC, M00staff commented on src/actions/userProfilePublic.js
> +        // Option 1: api remains consistent for all users and we remove here on FE
i like option 2

avoids mutating data on the frontend 🤷

2023-07-04 23:28 UTC, M00staff commented on src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
> +                  onClick={() => openPdf(true)}
Am I understanding this logic correctly?

- if on IE11, the `Employee Profile` link will download an (un-redacted) PDF 

- if **not** on IE11, it will open the sweet alert window and render the (un-redacted) PDF

- but in both cases - they can download the redacted PDF?

I think a switch or a nested if statement, might make this easier to follow - or some comments explaining what's going on and why.

2023-07-05 00:00 UTC, M00staff requested changes
- decide on implementation
- clear up IE11 logic

2023-07-05 11:51 UTC, elizabeth-jimenez commented on src/actions/userProfilePublic.js
> +        // Option 1: api remains consistent for all users and we remove here on FE
Option 1 wouldn't mutate the data on the FE, would just be more conditional rendering

2023-07-05 11:56 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
> +                  onClick={() => openPdf(true)}
Yep - your logic follows. Except if they have no unredacted we will show them that in the PDF viewer and auto download. TBD

I'll add some comments

2023-07-05 12:43 UTC, elizabeth-jimenez commented
@M00staff went ahead and added a variable that abstracts the IE11 logic.

2023-07-05 13:29 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/UserProfileGeneralInformation.jsx
> +                  onClick={() => openPdf(true)}
exactly one will be unredacted

2023-07-05 13:54 UTC, M00staff approved these changes

2023-07-05 14:08 UTC, merged