Tm 4584 UI projected vacancies page and search
MetaPhase-Consulting/State-TalentMAP pull request #2597
Opened 2023-06-28 19:04 UTC by cagbakwu

[Ticket] https://metaphase.atlassian.net/browse/TM-4584
STILL WORKING ON, this is the first half.

-Created projected vacancy search UI page
-Added redux files for  search section

2023-06-29 14:21 UTC, pveland621 commented
Menu styling is a little off on the dashboard landing page:
<img width="199" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/1dd2192d-c47c-42bf-a30b-106f08522da5">

This is definitely the longest (by character) menu option we have, so maybe just have a hanging indent:
<img width="200" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/00e6604c-03f0-40b3-ad47-a3e58c696a6d">

It does fix itself when you go to the PV page though - but even then we might need a tiny bit of padding on the right:
<img width="305" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/faaf4443-ffe6-44d9-a178-b38f1cc4aeb4">

2023-06-29 14:25 UTC, pveland621 commented
Weirdly, at different resolutions, the label and dropdown is spaced wrong by just a bit:
<img width="340" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/30ddec78-b4cc-43ca-a197-3e96592c4f68">

And again, super tiny nitpick but on 1100px resolution, spacing is a little off:
<img width="344" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/5d007cfa-05e9-4c9a-818e-2f8df6421c11">

Spacing @ 1600px:
<img width="1160" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/e294c350-4905-4fde-a5e3-d80c76ae35d8">

2023-06-29 14:29 UTC, pveland621 commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  const [selectedBureaus, setSelectedBureaus] = useState(get(userSelections, 'selectedBureaus') || []);
There's no way you could've known, but we are trying to move away from using lodash, specifically lodash `get`. Instead, we are trying to move the project towards using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). It'd be a ton of refactoring for this component so I'll defer to other devs on whether or not you should spend the time just changing the `get`s to optional chaining.

2023-06-29 14:48 UTC, pveland621 commented on src/actions/projectedVacancy.js
> +}
awesome job on this but one tiny thing is we do want to send off the `editProjectedVacancyFetchDataLoading` as the last dispatch in the batch, as we use the loading state to determine when to render (like you did in this new component: 
<img width="794" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/3c2a1b75-dd11-42b0-b7c1-1440d1dc4913">
we always want the loading dispatch to be the first (when setting loading to true) and last (when setting loading to false) dispatches in the action, or as elizabeth likes to call it, a `loading sandwich`:
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/e7740d75-c7f3-4d78-a8aa-8c06b79af41a)

2023-06-29 14:51 UTC, pveland621 commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  function renderSelectionList({ items, selected, ...rest }) {
last thing, I noticed this is based on the `PanelMeetingAgendas` filter setup - i saw in the PR description that you still need to work on the dropdown options and content, just making sure that this is what you meant you needed to fix

2023-06-29 20:26 UTC, cagbakwu commented on src/actions/projectedVacancy.js
> +}
^^^ these visuals are great! @pveland621

2023-06-29 21:09 UTC, cagbakwu commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  const [selectedBureaus, setSelectedBureaus] = useState(get(userSelections, 'selectedBureaus') || []);
@pveland621 @M00staff  ok that sounds good, possibly could wait if no one has any objections? If everything is complete before end of sprint, I could go back through and refactor?

2023-06-30 14:31 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  const [selectedBureaus, setSelectedBureaus] = useState(get(userSelections, 'selectedBureaus') || []);
its actually not super difficult to swap - this line specifically would just look something like this:

`const [selectedBureaus, setSelectedBureaus] = useState(userSelections?.selectedBureaus || []);`

its one of the reasons I'm so vehemently anti-lodash lol - everything except maybe checking for deeply nested equality has an easy vanilla solution, at a fraction of the load time.

.. .all that being said - in the interest of time - and seeing as how we don't have it as a luxury - am 100% cool with keeping all the lodash here, as is

2023-06-30 14:41 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +                      valueKey="code"
Bid Cycles is being wonky - when you click one, it auto clicks all of them ... i think this should be `id` but there also might be something else amiss 🤔

<img width="369" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/1c433d26-286b-4cd5-a088-cf14128eaeed">

2023-06-30 14:42 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  };
you're gonna wanna clear our the rest of the filters here - i also had mine clear the search box ... not sure if that's right - but it made sense to me

<img width="1682" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/1b8298aa-a587-40c9-9612-0c4b82d6ebf8">

2023-06-30 14:45 UTC, M00staff commented on src/Components/ProfileMenu/NavLink/NavLink.jsx
> +                  <span style={{ display: 'flex' }}>
HAH! 

in-line styles - i miss those!

so handy

2023-06-30 14:54 UTC, M00staff commented on src/Components/ProfileMenu/NavLink/NavLink.jsx
> +                  <span style={{ display: 'flex' }}>
though - it looks like this breaks a little when the card gets expanded ... it might be that the new card we end up using doesn't have this issue 🤔
<img width="2098" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/0eea65cf-604c-4079-a666-170ac8c9245d">

2023-06-30 15:05 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +    dispatch(editProjectedVacancyFiltersFetchData(getQuery()));
so this will run the Query on page load when there are likely no filters ... i dont *THINK* that is expected behavior

i could be wrong on that though

2023-06-30 15:09 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +    dispatch(editProjectedVacancyFetchData(getQuery()));
and this dispatch will run the fetch query on the data every time you change a filter ... the way i had mine setup was to only run the `fetchDataQuery` when the submit button was pressed. 

i know `PanelMeetingAgendas` and `EmployeeAgendaSearch` and `Position Manager` all work a little differently from that (and each other)

.. might need more clarification on how this is supposed to function 🤔

2023-06-30 20:14 UTC, cagbakwu commented on src/Components/ProfileMenu/NavLink/NavLink.jsx
> +                  <span style={{ display: 'flex' }}>
@M00staff I added some CSS "Magic" to resolve this.

2023-06-30 20:27 UTC, cagbakwu commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  };
@M00staff cleared!

2023-06-30 20:27 UTC, cagbakwu commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +                      valueKey="code"
@M00staff this was weird but its resolved now

2023-06-30 20:30 UTC, cagbakwu commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +    dispatch(editProjectedVacancyFetchData(getQuery()));
@M00staff if this changes, I can revise it. For now I can leave it as is.

2023-07-03 10:31 UTC, jlam-mpc commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  const cycleOptions = uniqBy(sortBy(get(cycles, 'data'), [(c) => c.custom_description]), 'custom_description');
Some of these are written plural and some are singular (same goes for the mockups) while the functionality of the filters is multi-select for all of these. Is it confirmed that we can select multiple for all of these fields or do we need to convert some of them to radio buttons and non-array types?

2023-07-03 10:35 UTC, jlam-mpc commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +      <Spinner type="projected-vacancy-filters" size="small" /> :
While the page is close to perfectly styled, I have some suggestions on the organization of it to reduce css bloat and reuse some common style blocks throughout the app. Position Manager Page, Publishable Position Page, and Projected Vacancy Page (potentially more) all use very similar styles. In my Publishable Positions Page, I'm reusing most of the styles in _bureau (following Position Manager Page) and added an umbrella className to narrow down to specifics. I think it'd be good to eventually refactor all 3 components to have generic classes with as much of the same style declarations as possible.

TLDR;
There is some mild CSS redundancy, you should leave the styling you have for now, we should refactor the styles/classes for this component after it's been merged to align with Position Manager and Publishable Positions

2023-07-03 13:32 UTC, cagbakwu commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +      <Spinner type="projected-vacancy-filters" size="small" /> :
@jlam-mpc yea I noticed the same stylings as well. I think refactoring the css afterwards is a great idea.

2023-07-03 13:57 UTC, cagbakwu commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  const cycleOptions = uniqBy(sortBy(get(cycles, 'data'), [(c) => c.custom_description]), 'custom_description');
@jlam-mpc from the other search pages, they all have multi selects and from the screenshots provided. I could verify if they want to change or not.

2023-07-03 17:03 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +      selectedBidCycle,
just an FYI - this guy was missing in a few places so it wouldn't trigger the 'clear filters' button, or be sent to the action ... i just added it, so you should pull

2023-07-03 17:05 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +    dispatch(editProjectedVacancyFetchData(getQuery()));
yea - based on the slack convo, i think we're good here

2023-07-03 17:15 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +    selectedPost,
this was also missing - just added it

2023-07-03 17:21 UTC, M00staff commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +  function renderSelectionList({ items, selected, ...rest }) {
actually - dont worry about trimming this down, ill abstract it all in another PR

2023-07-03 18:16 UTC, cagbakwu commented on src/Components/BureauPage/ProjectedVacancySearch/EditProjectedVacancyDetails.jsx
> +    selectedPost,
@M00staff ah thanks, I thought I added them but it probably got lost amongst the other calls haha.

2023-07-05 03:32 UTC, M00staff approved these changes
This should be OK to merge in - no need to worry about updating the card, as that will be in another ticket.

A few things though:

I did a bunch of renaming - there will be a separate ticket that handles editing the vacancies that this search page produces ... the naming might have gotten a little complicated at that point (edit was used all over the place, even though we aren't editing anything, yet)... make sure to pull and click through and verify I didn't bonk anything

Also,
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/a771075b-d00a-44a8-bc24-1958e39bbf64)

I don't **think** this ^^ set of actions & reducers are doing anything, or used anywhere... you get generic filter options to use from `filtersFetchData`, and when they are selected and stored in Redux - they are stored in the `projectedVacancySelections` reducer.

Unless you were planning on using them for something (or if I'm off) get rid of them.

2023-07-05 05:15 UTC, M00staff requested changes
actually scratch that - there is something wonky with your test suite
<img width="169" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/b8ddfbec-1283-4982-a14a-a3d611ba1286">
it should actually be failing at the `server` step ... there's probably a typo somewhere

2023-07-05 14:33 UTC, M00staff approved these changes

2023-07-05 15:04 UTC, merged