TM-3813, Cycle Management - New Page & Search
MetaPhase-Consulting/State-TalentMAP pull request #2600
Opened 2023-06-30 05:29 UTC by M00staff

Marked as WiP - but all its missing is handling for pagination

[Ticket](https://metaphase.atlassian.net/browse/TM-3818)

<img width="2102" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/34f2250c-b015-4273-8a4d-6b5c94f0c5e6">

2023-06-30 05:31 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +  ];
there is a `references/status` endpoint - and we also use a status filter elsewhere, but the ticket specifically mentions that status should be 
```
Status (drop down)
Active
Closed
Proposed
Merged

2023-06-30 05:31 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +                <Picky
oops - need to make this a required field

2023-06-30 05:34 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +    'cycle-date-end': isDate(selectedDates?.[1]) ? startOfDay(selectedDates?.[1]).toJSON() : '',
we get to decide on the naming for the URL params, right?

2023-06-30 05:34 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +        {...rest}
prolly dont need this 🤔

2023-06-30 05:37 UTC, M00staff commented on src/actions/cycleManagement.js
> +    console.log(query);
ill remove these when closer to being able to merge

2023-06-30 19:01 UTC, cagbakwu commented on src/actions/cycleManagement.js
> +            dispatch(cycleManagementFetchDataLoading(true));
@M00staff I was told that if cycleManagementFetchDataLoading is true that it needed to be first in the list of dispatches.

2023-06-30 19:07 UTC, cagbakwu requested changes
cycleManagementFetchDataLoading is my main question

2023-07-03 17:49 UTC, scott062 commented
Check light mode

2023-07-03 17:53 UTC, scott062 commented on src/Components/BureauPage/BureauPage.jsx
> +        <Route path="/profile/bureau/cyclemanagement" render={() => <CycleManagement />} />
AOs need it too?

2023-07-03 17:55 UTC, scott062 commented on src/Constants/Menu.js
> +          'bureau_user',
AO too?

2023-07-03 17:58 UTC, scott062 commented
Make sure userSelections is working. I see actions to save filters but when I navigate and come back to the page - they are reset anyways.

2023-07-03 18:07 UTC, scott062 commented on src/sass/_bureau.scss
> +    grid-template-columns: repeat(auto-fill,minmax(33%, 1fr));
I don't know about the spacing on just 3 filters - not sure what would be better but seems very wide

2023-07-03 18:42 UTC, M00staff commented on src/sass/_bureau.scss
> +    grid-template-columns: repeat(auto-fill,minmax(33%, 1fr));
fixed!
<img width="2215" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/08019863-2463-41d9-a843-1b35abf7c111">

2023-07-03 19:15 UTC, M00staff commented on src/Components/BureauPage/BureauPage.jsx
> +        <Route path="/profile/bureau/cyclemanagement" render={() => <CycleManagement />} />
added

2023-07-03 19:15 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +  ];
will add this in the next PR that will render the cards & data

2023-07-03 19:16 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +        {...rest}
going to abstract this whole thing to a util function in a separate PR

2023-07-03 19:23 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +                <Picky
the filters will now search onChange

2023-07-03 20:12 UTC, cagbakwu approved these changes
Looks good to merge 👍

2023-07-05 12:29 UTC, jlam-mpc commented on src/Components/BureauPage/BureauPage.jsx
> +        <Route path="/profile/ao/cyclemanagement" render={() => <CycleManagement />} isAO />
Will we eventually need to pass in props globally like some of the other components do? If so should we all set up the design of those props now or later?

2023-07-05 13:14 UTC, M00staff commented on src/Components/BureauPage/BureauPage.jsx
> +        <Route path="/profile/ao/cyclemanagement" render={() => <CycleManagement />} isAO />
it could be either/or considering the page doesn't do anything right now - and that there is another ticket in the queue to render the results.

2023-07-05 13:37 UTC, merged