[TM-4581] Publishable Positions Page
MetaPhase-Consulting/State-TalentMAP pull request #2602
Opened 2023-07-03 10:48 UTC by jlam-mpc

Dual Merge: 
- [API PR](linkToAPIPR)
- [Mock PR](linkToMockPR)

[Ticket](linkToTicket)

2023-07-03 16:11 UTC, cagbakwu requested changes

2023-07-03 16:11 UTC, cagbakwu commented on src/Components/EditPositionDetails/EditPositionDetails.jsx
> +  const statuses = genericFilters$.find(f => get(f, 'item.description') === 'publishableStatus');
The team is slowly moving away from using lodash, and looking into optional chaining. I've made a few of the changes in my PR but not all. Eventually we will look to get rid of it completely. I think this is fine for now though unless you want to make those changes now. There can be some refactors after merging.

2023-07-05 03:39 UTC, M00staff commented on src/Components/EditPositionDetails/EditPositionDetails.jsx
> +  // } = props;
?

2023-07-05 03:44 UTC, M00staff commented on src/Components/EditPositionDetails/EditPositionDetails.jsx
> +  const statuses = genericFilters$.find(f => get(f, 'item.description') === 'publishableStatus');
i **think** an example would look something like this:
```
const bureaus = genericFilters$.find(f => f?.item?.description === 'region');
const bureauOptions = bureaus?.data?.length
    ? [...new Set(bureaus.data)].sort(b => b.short_description) : [];
```
depending on the description and what you wanna sort by

2023-07-05 03:50 UTC, M00staff commented on src/Components/EditPositionDetails/EditPositionDetails.jsx
> +  const statuses = genericFilters$.find(f => get(f, 'item.description') === 'publishableStatus');
you can keep it as is for expedience

2023-07-05 03:55 UTC, M00staff commented on src/Components/EditPositionDetails/EditPositionDetails.jsx
> +      selectedSkills,
```suggestion
      selectedSkills,
      selectedBidCycle,
      selectedStatus,
```

2023-07-05 03:59 UTC, M00staff commented
I, too, am trying to figure out where publishable statuses come from - i have mine hardcoded for now, we can tweak it down the road if you wrap this before it's figured out.

2023-07-05 04:03 UTC, M00staff commented
was this always there?
<img width="270" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/5090e7de-689e-493e-a7f2-ffff642b4aaa">

2023-07-05 12:05 UTC, jlam-mpc commented
> was this always there? <img alt="image" width="270" src="https://user-images.githubusercontent.com/12723877/251033467-5090e7de-689e-493e-a7f2-ffff642b4aaa.png">

It is, it just looked different before (using absolute positioning and was inside the card on the right corner). I just removed the style block for it because in my new component it's not using the styles in the old sheet anymore.

2023-07-05 12:54 UTC, jlam-mpc commented on src/Components/EditPositionDetails/EditPositionDetails.jsx
> +  // } = props;
I based it off of the usage of the other bureau pages and thought we'd eventually need to pass these props in globally but I removed them in the latest because if that were the case we could add them in.

2023-07-05 15:09 UTC, M00staff approved these changes

2023-07-05 15:32 UTC, merged