changed the hard sidebar width to change with sidebar is minimized
MetaPhase-Consulting/State-TalentMAP pull request #2605
Opened 2023-07-06 21:26 UTC by cagbakwu

Changed the width of the profile sidebar to be dynamic. Previous styling added extra white space when the bar was minimized.
<img width="962" alt="Screenshot 2023-07-06 at 4 25 40 PM" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/5ce42352-922b-48fc-9740-20242e7ee045">
<img width="962" alt="Screenshot 2023-07-06 at 4 25 31 PM" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/97eae306-a418-4deb-ba07-5aba7b467a61">

2023-07-11 12:59 UTC, elizabeth-jimenez commented on src/Components/ProfileMenu/NavLink/NavLink.jsx
>                  this.wrapInLink( // wrap our element
`<span style={{ display: 'flex' }}>` for this one, we can add a class and then put the flex on that class over in the css file

2023-07-11 13:00 UTC, elizabeth-jimenez commented on src/Components/ProfileMenu/NavLink/NavLink.jsx
>                  this.wrapInLink( // wrap our element
`word-wrap: break-word;` can go in `.title-container`

2023-07-11 13:06 UTC, elizabeth-jimenez commented
? Did you make the max width 300 because at smaller sizes the text starts to creep up on the icon? If so, play around with the `$total-padding` variable. `.fa-container` uses it

2023-07-11 20:29 UTC, elizabeth-jimenez commented
Approved Pending Feedback: inline styles to css file

2023-07-12 19:26 UTC, cagbakwu commented
@elizabeth-jimenez good deal, just transferred css over and removed inline styles!

2023-07-12 20:38 UTC, elizabeth-jimenez commented on src/sass/_profile.scss
> +    width: 300px;
```suggestion
    width: 230px;
```

2023-07-12 20:41 UTC, elizabeth-jimenez commented on src/sass/_profile.scss
on L606
```
    .fa-container {
      min-width: 30px;
    }
```

2023-07-12 20:41 UTC, elizabeth-jimenez commented on src/sass/_profile.scss
> +    width: 300px;
now that we've moved where our max-width goes, we can stand to reduce it a few pixels

2023-07-12 20:46 UTC, elizabeth-jimenez commented on src/sass/_profile.scss
> +  margin-right: $profile-title-wrapper;
we'll want to undo this change - notice the padding it adds:
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/9f37ccdc-00de-42b4-a483-fa4ddc56a3a2)
green(top) is this branch
pink(bottom) is dev

2023-07-12 20:47 UTC, elizabeth-jimenez commented on src/sass/_profile.scss
> +  margin-right: $profile-title-wrapper;
sorry may have been unclear, it would be fine if we didnt highlight the current menu item we are on - changed the color above to emphasize I mean

2023-07-12 20:48 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/e8109e33-910b-42a6-a080-20323fab1ea3)
What the menu should look like after the 3 changes

2023-07-12 23:15 UTC, cagbakwu commented on src/sass/_profile.scss
> +    width: 300px;
@elizabeth-jimenez yea true. This is helping me get back into CSS haha.

2023-07-13 14:19 UTC, cagbakwu commented on src/sass/_profile.scss
> +  margin-right: $profile-title-wrapper;
@elizabeth-jimenez ah yea good eye! I removed it.

2023-07-13 14:20 UTC, cagbakwu commented on src/sass/_profile.scss
@elizabeth-jimenez ended up not needing this padding

2023-07-13 14:23 UTC, cagbakwu commented on src/sass/_profile.scss
> +    width: 300px;
@elizabeth-jimenez only issue with reducing the sidebar from 300px with is that it causes issues with longer titles like "Projected vacancy management"
![Screenshot 2023-07-13 at 9 21 52 AM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/ca65773c-49c6-4b2e-bade-ffaefe2d5f74)
![Screenshot 2023-07-13 at 9 21 39 AM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/999679d9-6ba5-4264-8ac1-9b2b6993864d)

2023-07-13 14:49 UTC, scott062 commented
@cagbakwu @elizabeth-jimenez this ready for final approval?

2023-07-13 18:25 UTC, cagbakwu commented
@scott062 yes it looks good to go!

2023-07-13 19:54 UTC, M00staff commented on src/Components/ProfileMenu/NavLink/NavLink.jsx
> -                    <span className="title-container" style={{ wordWrap: 'break-word' }}>
😞 i like inline styles - especially for one off's like this

2023-07-13 19:59 UTC, M00staff commented on src/sass/_profile.scss
> +    width: 300px;
i noticed this too - i think it's fine either way.

2023-07-13 20:01 UTC, M00staff submitted a review, later dismissed
I didn't even know that button was there!

if you wanna change that one pixel length back to 300, I'd be OK with it 😉

Either way - looks great!

2023-07-13 20:02 UTC, M00staff requested changes
whoops - its failing a test

remember - its supposed to fail at the `server` step

![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/bc8aff98-de13-40f5-b2c2-38cc5a51e9ac)

2023-07-13 20:20 UTC, cagbakwu commented on src/Components/ProfileMenu/NavLink/NavLink.jsx
> -                    <span className="title-container" style={{ wordWrap: 'break-word' }}>
RIP inline :-(

2023-07-13 20:32 UTC, M00staff approved these changes
OK - NOW, we're looking good!

2023-07-13 20:45 UTC, merged