TM-3819, cycle search results
MetaPhase-Consulting/State-TalentMAP pull request #2606
Opened 2023-07-07 01:20 UTC by M00staff

Might as well throw this up for a review while I'm out

[Ticket](https://metaphase.atlassian.net/browse/TM-3819)

<img width="2010" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/4f16362c-c46a-4434-8b99-1c0b1ec01726">

2023-07-07 01:34 UTC, M00staff commented on src/Components/CycleManagement/CycleSearchCard.jsx
> +  const cycleLink = `/profile/bureau/cyclemanagement/${id}`;
@pveland621 ^^ this is going to link to the page you're building out .. the naming and pattern is up to you, this is just a placeholder

2023-07-12 13:50 UTC, elizabeth-jimenez commented
We'll want to set up pagination in this PR

2023-07-12 13:53 UTC, elizabeth-jimenez commented
The designs dont have a left border - is that intentional?

2023-07-12 13:54 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/ca01d7bf-aba4-49d1-bd04-6a9ffcc42189)
We don't want text to stack(CycleStart) before it absolutely has to

2023-07-12 14:00 UTC, elizabeth-jimenez commented
You'll also want to add a shadow to your cards.

2023-07-12 14:02 UTC, elizabeth-jimenez requested changes
- Pagination
- Left border
- Stacking Text
- Shadow

2023-07-12 17:26 UTC, elizabeth-jimenez commented
Additional changes:
- Icon discrepancy between menu and header.
- i think we are good to remove 'Search for an existing cycle' - i think that's a left over label from the search box
- honestly we might be ok to remove 'Cycle Search' too - gonna confirm with Tim

2023-07-13 09:10 UTC, M00staff commented on src/actions/cycleManagement.js
> +});
I think everything above was overkill - but i wasn't sure how best to make sure the results per page for the pagination was working properly 🤷

need to update the mock and what not to be sure of the rest of the pagination - but I'm sure that is way out of scope for this ticket.

2023-07-13 18:29 UTC, cagbakwu commented
> Might as well throw this up for a review while I'm out - feel free to go willy nilly and i'll address when i get back
> 
> [Ticket](https://metaphase.atlassian.net/browse/TM-3819)
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/12723877/251610784-4f16362c-c46a-4434-8b99-1c0b1ec01726.png">

Dark mode for the win!

2023-07-13 19:43 UTC, cagbakwu approved these changes
Besides the CSS variables to use, it looks good to me.

2023-07-13 20:08 UTC, M00staff commented on src/actions/cycleManagement.js
> +    // api().get(endpoint)
commented out until we get data from the mock

2023-07-13 20:24 UTC, scott062 approved these changes

2023-07-13 20:25 UTC, merged