[TM-3820] Edit Publishable Position Card
MetaPhase-Consulting/State-TalentMAP pull request #2616
Opened 2023-07-14 05:16 UTC by jlam-mpc

Features:
- Added form prop to PublishablePositionCard component to activate and format the edit mode card
- Added basic input fields and state management
- Styled form

Not Complete:
- Array of cycle inputs
  - Array state management
  - Adding new input fields
  - Action on "Add Another Cycle"
- Clear text button on cycle input field ("X")
- Dummy redux state management in preparation for when the component is linked with the API

Note:

The results object doesn't contain information for publishable status, exclude, and cycle names yet (I don't believe) so right now there are just placeholders for those fields. The position details is using the actual value though.

[TM-3820](https://metaphase.atlassian.net/browse/TM-3820)

2023-07-17 15:41 UTC, cagbakwu commented on src/sass/_positionContent.scss
> +      padding: 0 35px 0 10.5px;
Is it possible to use another method vs the decimal route? I'm thinking about how things break down sometimes due to decimals.

2023-07-17 15:42 UTC, cagbakwu requested changes
Besides the CSS question, it looks good.

2023-07-17 17:44 UTC, elizabeth-jimenez commented on src/sass/_positionContent.scss
> +      padding: 0 35px 0 10.5px;
I'll increase to 11!

2023-07-17 17:49 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/7ac58679-781e-48f7-9f4a-5d545f3b7792)
nooo what have i done 😓

2023-07-17 18:28 UTC, cagbakwu commented
> ![image](https://user-images.githubusercontent.com/23065001/254026484-7ac58679-781e-48f7-9f4a-5d545f3b7792.png) nooo what have i done 😓 fixing - can't replicate, not sure what was happening here 🤷‍♀️ - it was the broswer zoom in size

(╯°□°)╯︵ ┻━┻     haha

2023-07-18 12:51 UTC, elizabeth-jimenez commented on src/actions/editPositionDetails.js
> -export function editPositionDetailsFiltersFetchDataErrored(bool) {
Im going to be updating a lot of the naming in this file in another PR

2023-07-18 12:52 UTC, cagbakwu commented on src/actions/editPositionDetails.js
> +          dispatch(editPositionDetailsEditDataLoading(false));
Shouldn't this be last to call since its set to false?

2023-07-18 12:53 UTC, cagbakwu commented on src/actions/editPositionDetails.js
> +            dispatch(editPositionDetailsEditDataLoading(true));
ditto here, shouldn't this be called first since its true?

2023-07-18 12:53 UTC, elizabeth-jimenez commented on src/actions/editPositionDetails.js
> +          dispatch(editPositionDetailsEditDataLoading(false));
😱 yes!

2023-07-18 12:53 UTC, cagbakwu commented on src/actions/editPositionDetails.js
> +      dispatch(editPositionDetailsFetchDataLoading(false));
Same as the bottom comment about editPositionDetailsEditDataLoading

2023-07-18 12:55 UTC, cagbakwu requested changes
curious about the editPositionDetailsEditDataLoading action position. When its set to false, it should be called last vs when its set to true, it should be called first.

2023-07-18 12:55 UTC, elizabeth-jimenez commented on src/actions/editPositionDetails.js
> +          dispatch(editPositionDetailsEditDataLoading(false));
pushed update - nice find!

2023-07-18 13:03 UTC, elizabeth-jimenez commented on src/actions/editPositionDetails.js
> +            dispatch(editPositionDetailsEditDataLoading(true));
🎊 yes! I don't think we've done it this way for Cancels, but it does make sense for it to be loading true first!

2023-07-18 14:03 UTC, cagbakwu approved these changes
Looks good

2023-07-18 14:20 UTC, merged