TM-4583, cycle position search edit
MetaPhase-Consulting/State-TalentMAP pull request #2628
Opened 2023-07-19 03:23 UTC by M00staff

Will only get the error toasts unless i jimmy it to do other-wise.

I can populate all of this with much more robust fake data - but that feels kind of like a waste of time 🤷

<img width="1786" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/fef9c6e7-1cba-439b-af7a-6e2a1c459473">

<img width="716" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/d56ee35d-b860-40cd-9613-feab78788eb6">

<img width="400" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/3ed11f55-bb57-4d11-9adb-3d730923ab3b">

[Ticket](https://metaphase.atlassian.net/browse/TM-4583)

2023-07-21 12:33 UTC, cagbakwu commented on src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
> +                  <CyclePositionCard data={data} cycle={loadedCycle} dispatch={dispatch} isAO />)}
I never thought of passing dispatch like this. 🚀🚀🚀🚀

2023-07-21 18:43 UTC, cagbakwu approved these changes
Looks good

2023-07-24 12:14 UTC, elizabeth-jimenez commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +  const removePosition = () => {
Instead of copy/pasting this from PositionExpandableContent.jsx, check what I did [here](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2626/files#r1272180119) - it's a quick change to allow the component to accept custom cancel text

2023-07-24 12:15 UTC, elizabeth-jimenez commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +    handleSubmit: () => dispatch(cyclePositionEdit(data, incumbent, status)),
🙌

2023-07-24 12:17 UTC, elizabeth-jimenez requested changes
Cancel text/form

2023-07-24 14:56 UTC, M00staff commented on src/Components/CycleManagement/CyclePositionSearch/CyclePositionSearch.jsx
> +                  <CyclePositionCard data={data} cycle={loadedCycle} dispatch={dispatch} isAO />)}
so fun fact - i actually HAVE to pass the dispatch function like this ... since the card uses an Object Oriented pattern (at least i think that is why), i can't call the `useDispatch()` hook properly inside of it. 

we actually had to do something similar to pass useDispatch into sweet alert

2023-07-24 16:32 UTC, M00staff commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +  const removePosition = () => {
yea - so my only issue with that, is that this logic & alert is for removing the position entirely (not canceling out of the edit mode), which i think is unique to the Cycle Position Search cards. 

that was my bad as i didn't push up a touch up (commit)(https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2628/commits/e1a17d71942b506693e7a01152852c8e2081e886) that makes it a little more clear.

the `Yes` button here will have a different handling vs the `Submit` button on the `PositionExpandableContent` page (unless we want to pass down the `dispatch(cyclePositionRemove(data)` logic as well ... but, on top of that - the If statement on the next line is conditionally checking to see if there is an incumbent in the position - which will cause the alert to come up before the user can remove the position completely from the cycle.

2023-07-24 19:21 UTC, elizabeth-jimenez commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +  const removePosition = () => {
Ah i see! Nah, my bad for missing that!

2023-07-24 19:52 UTC, elizabeth-jimenez commented on src/sass/_positionContent.scss
> +    margin-top: 25px;
```suggestion
    box-shadow: 2px 2px 2px rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(228, 229, 230, 1);
    padding: 5px 20px;
```

Stole the first 2 straight from the designs lol
Before suggested changes:
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/f254cf8b-5dbf-47e8-a050-33beaea5b381)
After suggested changes:
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/81154d22-9c13-4ef3-9495-756439f7e993)

2023-07-24 19:53 UTC, elizabeth-jimenez commented on src/sass/_positionContent.scss
> +    margin-top: 25px;
idk how to remove the margin-top suggestion; no change requested there

2023-07-24 20:14 UTC, elizabeth-jimenez commented on src/Constants/SystemMessages.js
> +export const REMOVE_CYCLE_POSITION_ERROR = 'There was an issue attempting to remove this Position Number. Please try again.';
```suggestion
export const REMOVE_CYCLE_POSITION_SUCCESS_TITLE = 'Cycle Position Removed';
export const REMOVE_CYCLE_POSITION_SUCCESS = 'Cycle Position has been removed.';
export const REMOVE_CYCLE_POSITION_ERROR_TITLE = 'Cycle Position Delete Error';
export const REMOVE_CYCLE_POSITION_ERROR = 'There was an issue attempting to remove this Cycle Position. Please try again.';
```

I know the ticket said Position Number, :/ but that sounds weird, tbh

2023-07-24 20:15 UTC, elizabeth-jimenez commented on src/Constants/SystemMessages.js
> +export const EDIT_CYCLE_POSITION_ERROR = 'There was an issue attempting to update this Position. Please try again.';
```suggestion
export const EDIT_CYCLE_POSITION_SUCCESS_TITLE = 'Cycle Position Updated';
export const EDIT_CYCLE_POSITION_SUCCESS = 'The Cycle Position has been updated';
export const EDIT_CYCLE_POSITION_ERROR_TITLE = 'Cycle Position Edit Error';
export const EDIT_CYCLE_POSITION_ERROR = 'There was an issue attempting to update this Cycle Position. Please try again.';
```

2023-07-24 20:16 UTC, elizabeth-jimenez commented on src/Constants/SystemMessages.js
> +export const REMOVE_CYCLE_POSITION_ERROR = 'There was an issue attempting to remove this Position Number. Please try again.';
I was gonna suggest just `Position`, but when I ran it by Scott, he said `Cycle Position` made more sense

2023-07-24 20:20 UTC, elizabeth-jimenez commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +      'Location': getPostName(get(pos, 'post')) || NO_POST,
wow wow Lodash get 😱

2023-07-24 20:30 UTC, M00staff commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +      'Location': getPostName(get(pos, 'post')) || NO_POST,
i can't believe i let that slip by!!!!😱

2023-07-24 20:32 UTC, elizabeth-jimenez commented
I feel bad cause you asked this in UI/UX, but I think we are supposed to be editing the TED of the incumbent, even tho the designs show the actual Incumbent - ima ask and see

2023-07-24 20:37 UTC, elizabeth-jimenez commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +      'Location': getPostName(get(pos, 'post')) || NO_POST,
I let the Loading sandwich slip by on my PR last week and couldn't believe myself either lol

2023-07-24 20:41 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/f1154885-3775-4810-9801-209de9e26088)
I think when we go to Edit Mode, all the fields that are being Edited will be removed from the top part - so in this case, it'll be Status and Incumbent TED - Incumbent will be weird cause it has Incumbent and TED grouped together tho, so maybe we just show the name on Edit Mode 🤔  The ACs say it, but the designs are a bit misleading.

2023-07-24 20:42 UTC, elizabeth-jimenez commented
Trickle Review Complete ✅

2023-07-25 16:50 UTC, elizabeth-jimenez approved these changes

2023-07-25 16:54 UTC, elizabeth-jimenez commented
Potentially quite a bit of changes will be needed for these cards dependent on further research, so we can just capture them all over there

2023-07-26 03:33 UTC, merged