TM-4521: Pay Plan field - Panel Agenda items
MetaPhase-Consulting/State-TalentMAP pull request #2651
Opened 2023-07-31 20:29 UTC by pveland621

WIP - still need to make sure I added to all the right places for the new fields

Dual Merge: 
- [API PR](linkToAPIPR)

[Ticket](https://metaphase.atlassian.net/browse/TM-4521)

2023-08-14 17:20 UTC, elizabeth-jimenez commented
@pveland621 not seeing this in AIM

2023-08-14 17:24 UTC, elizabeth-jimenez commented on src/Components/Agenda/AgendaItemTimeline/AgendaItemTimeline.jsx
> +        pay_plan: null,
?

2023-08-14 17:25 UTC, elizabeth-jimenez commented on src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
> +      content: (<div>{get(leg, 'pay_plan') || defaultSepText || DEFAULT_TEXT}</div>),
intentional? the `defaultSepText`

2023-08-14 17:47 UTC, elizabeth-jimenez commented on src/Components/Agenda/AgendaItemCard/AgendaItemCard.jsx
> +        pay_plan: PropTypes.string,
? intentional?

2023-08-14 18:03 UTC, elizabeth-jimenez commented
Reviewed - few things to address

2023-08-15 16:03 UTC, jlam-mpc reviewed
I know you're pending changes but wanted to just submit this first and do a second review after.

Other than the places Elizabeth pointed out where it seems accidental or missing usage,

The AC says

Add Pay Plan Field to the following pages:
Panel Meeting 
Agenda Item Maintenance
Agenda Item History

But there are no mockups. Are you still intending to throw Pay Plan into Panel Meeting Cards? Or am I misunderstanding that requirement?

2023-08-15 18:58 UTC, jlam-mpc approved these changes
Everything I said in my previous review was addressed! I'll go ahead and approve but just wanted to clarify the requirements for Pay Plan in maintenance. If it's definitely not a selectable field then I think it's ready for merge.

And a minor comment I'm wondering is since this is a new field should we consider the hierarchy it takes on in the same context as the other fields.

2023-08-15 18:58 UTC, jlam-mpc commented on src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
> +    },
If this isn't a dropdown should we also order it above the selectable fields so that it's grouped with the static ones? I guess it doesn't really matter but I was curious of hierarchy of info matters for these UI changes.

2023-08-15 20:13 UTC, jlam-mpc commented on src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
> +    },
Elizabeth talked to me clarifying the nature of the fields and Pay Plan is also considered a field that would show data differently to delineate that the Agenda Leg is a separation. The original conditions you had using `defaultSepText` was correct!

2023-08-15 20:13 UTC, jlam-mpc requested changes
Need to change the way Pay Plan is displayed in AgendaLeg after getting clarification from Elizabeth

2023-08-15 20:43 UTC, pveland621 commented on src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
> +    },
> If this isn't a dropdown should we also order it above the selectable fields so that it's grouped with the static ones? I guess it doesn't really matter but I was curious of hierarchy of info matters for these UI changes.

a good question, we can ask at demo or more likely just default to "if chris and robin see it and don't like it in that order, they'll say something" because i didn't get a mockup or a special note in the ticket to do so

2023-08-16 13:20 UTC, jlam-mpc approved these changes

2023-08-16 13:20 UTC, merged