TM-4708-Manage-Post-Access
MetaPhase-Consulting/State-TalentMAP pull request #2667
Opened 2023-08-13 20:13 UTC by cagbakwu

https://metaphase.atlassian.net/browse/TM-4708

-Created new manage post access page
-Added filter search section
-Added checkbox selections
-Added redux
-Added toast alerts
<img width="757" alt="Screenshot 2023-08-13 at 3 08 43 PM" src="https://github.com/USStateDept/State-TalentMAP/assets/135657303/c950599a-9af2-4790-8692-7faca55abe6b">
<img width="757" alt="Screenshot 2023-08-13 at 3 08 58 PM" src="https://github.com/USStateDept/State-TalentMAP/assets/135657303/bd6a139b-c7ae-4135-a24c-0e42b1cc17f7">
<img width="757" alt="Screenshot 2023-08-13 at 3 09 07 PM" src="https://github.com/USStateDept/State-TalentMAP/assets/135657303/0fe970de-667b-4093-b888-25b32a6d2cd1">

2023-08-13 20:14 UTC, cagbakwu commented
Will adjust the checkbox positioning! 🚀

2023-08-14 17:51 UTC, M00staff commented on src/actions/managePostAccess.js
> +  { id: 1, name: 'Row 1', description: 'FSBid Organization Bidders', value: 'Frank Jones', date: '00000005 (Trade Negot)', isChecked: false },
the data isn't going to have this `isChecked` property - you should be able to use the IDs of the data to find out if its checked

2023-08-14 17:52 UTC, M00staff commented on src/Components/ManagePostAccess/ManagePostAccess.jsx
> +    if (selectedCount !== 0) dispatch(toastSuccess('Access has been granted!', 'Success'));
instead of dispatching the toast - dispatch the correct action here

2023-08-14 17:57 UTC, M00staff commented on src/Components/ManagePostAccess/ManagePostAccess.jsx
> +            <PostAccessCard
i think you can get by without this having to be it's own component - that's what i ended up doing ... you also wont have to pass down that `checkCount` variable

2023-08-14 18:09 UTC, M00staff commented on src/sass/_postAccess.scss
> +      }
i fixed the check box issue with this bit 
<img width="185" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/027dbde5-c772-4841-8b86-c21be9aae63e">

2023-08-14 18:16 UTC, M00staff requested changes
a few changes on first glance
- remove the card component and just keep the logic in the parent
- fire the correct actions instead of using the toasts directly
- move away from using that `isChecked` property on the data
- fix the wonky CSS on the check boxes 

you can look at my PR as an example - also, use that time to review my PR 

will go through and do another round this evening

2023-08-14 19:43 UTC, elizabeth-jimenez commented on src/sass/_postAccess.scss
> +
💔 ouch - poor `filters-sizing-config`

2023-08-15 05:02 UTC, M00staff commented on src/sass/_postAccess.scss
> +
updated!

2023-08-15 13:16 UTC, cagbakwu commented on src/sass/_postAccess.scss
> +
haha yea this was before looking at the consolidated filter section.

2023-08-15 18:43 UTC, M00staff commented
looks good - I'm gonna update the system messages to be a little more clear and can handle the merge conflicts since its all likely conflicting with my stuff

2023-08-15 19:21 UTC, M00staff approved these changes
👍

2023-08-15 20:04 UTC, merged