TM-4735-CDO-D3.0
MetaPhase-Consulting/State-TalentMAP pull request #2678
Opened 2023-08-29 00:51 UTC by cagbakwu

https://metaphase.atlassian.net/browse/TM-4735

-Added eligible and cusp bidders to filter dropdown
-Added eligible and cusp bidders ribbons to cards
-Added a toggle to cards
-Created OS email(read only)
-Created editable comments and alt email section
![Screenshot 2023-08-28 at 7 41 39 PM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/4c0a5204-265c-4a6b-9a64-c1afb8537e5f)
![Screenshot 2023-08-28 at 4 48 44 PM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/541df97f-daef-49de-8837-156f0719bfc5)
![Screenshot 2023-08-28 at 7 42 14 PM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/d5268053-51c4-44bd-9453-330459ca7e03)

2023-09-07 00:39 UTC, M00staff commented
it looks to me like the flags only got added to the cards in the list view... is that the way it's meant to be?

cause they're not on the grid view

<img width="147" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/631ffe77-54fe-49b7-80ba-cb8d50e075a1">
<img width="1109" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/743fb3e0-62f3-4da2-b302-fb03602f8d07">

2023-09-07 00:57 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +            <dt>DOS Email:</dt><a href="mailto: example@gmail.com">{email}</a>
is `example@gmail.com` what you meant to place here?

2023-09-07 01:02 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +    dispatch(toastSuccess(`Changes saved for ${bidder}.`));
the dispatch function should be calling a Redux action, which would call the toast

you should be able to set the boilerplate up for that action & reducer - it would be saving the next person some work

2023-09-07 01:21 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +            <a href={`mailto: ${altEmail}`}>{altEmail}</a>
i think it's yelling about the space after the colon here

<img width="434" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/5b79ce02-efbe-4685-9bd5-209e06b505b4">

2023-09-07 01:34 UTC, M00staff commented
The ticket mentions an update to the Export functionality - i realize that you don't have access to the spreadsheet, but why no mention of it not being a part of the PR?

2023-09-07 01:48 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +  const eligible = get(userProfile, 'eligible', false);
If I'm understanding the spreadsheet right - then this value is going to come from the new endpoint 

I'm thinking i can make the call in the API layer as a part of the userProfile call and then add it to the return payload 🤔

... this is a note for myself, if anything

2023-09-07 01:49 UTC, M00staff commented
Going forward - please reach out to Tim before starting work on a ticket, and make sure you understand all of the asks.  

When wrapping up coding, reach out to him again - and do a screen share of what you have locally, so he can go over it with you, to make sure everything is there and looks right... that way we can spend more time reviewing the code, and less time making sure it works.

2023-09-09 20:27 UTC, cagbakwu commented
Unable to complete part 6 due to not having access. Screenshot below.
![Screenshot 2023-09-09 at 3 26 15 PM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/b75d5075-7b3a-4f42-9fa1-100326ec9c18)

2023-09-11 17:20 UTC, M00staff commented
We can add the Export Updates to the API ticket ... Is this ready to be reviewed?

There are merge conflicts that need to be addressed

2023-09-11 19:00 UTC, M00staff requested changes
merged conflicts, outstanding comments

2023-09-11 19:45 UTC, M00staff commented
so, i still dont see the cusp or eligible bidder flags on the cards?
<img width="1486" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/b26012da-3304-46ca-b2ea-c36776500e88">

2023-09-12 20:48 UTC, M00staff commented on src/actions/bidderPortfolio.js
> +}
yea - so half way there ... you'll also need the reducer & accompanying logic 

it will work similar to the `searchPostAccessRemove` action (only this will be a POST request)

wire the whole thing up - make sure it works and that the data that you want saved to the DB is being passed into the Action... keep in mind, whatever you don't do in this PR, will be work that i'll have to do, in the next - much more complicated - PR. 

you'd be helping me out.

2023-09-12 20:51 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +  const email = get(userProfile, 'cdos')[0]?.cdo_email || 'None listed';
I'm officially giving up on trying to get folks to stop using Lodash 😂

I will never understand the appeal

2023-09-12 21:06 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +    dispatch(bidderPortfolioDataSuccess(bidder));
yea - so right now, you're just passing the `bidder` variable into the action

2023-09-12 21:07 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +    dispatch(bidderPortfolioDataSuccess(bidder));
and just directly calling the success action ... you should be pretty familiar with the Redux pattern we use by now

2023-09-12 21:23 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +          <ToggleButton
OK - so this toggle doesn't do anything ... the ticket says:

<img width="393" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/2abe9288-77af-4d77-9379-16c8a6ee51bd">

but, I'm not sure what to make of that - do you know what they mean?  

If not, can you get some clarification?  I just don't know if there should be another frontend component to this part - or if this toggle should be connected to an API call

2023-09-12 21:35 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +            <dt>DOS Email:</dt><a href={`mailto:${email}`}>{email}</a>
can you add a space after the colon?  It looks a little cramped

<img width="365" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/ff90dec9-e3f0-47e0-81b1-fbfce11221b8">

2023-09-12 21:35 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +            <dt>Alt Email:</dt>
same - space after the colon

2023-09-12 21:37 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +              <dt>DOS Email:</dt><a href={`mailto: ${email}`}>{email}</a>
space after colon

2023-09-12 21:38 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +              <dt>Alt Email:</dt>
space after colon

2023-09-12 21:50 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +            <dt>Comments:</dt>
can you try moving the Emails to above the comments (so they look inline with the other key/value pairs) - in both views.

<img width="328" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/9d55e229-0fb6-4d8a-a296-37ba6e03c7f6">

and then setup the comments block to look like the Alt Email block in edit mode (so the word comments is on the top of the Text Box) - just in the list view (the card view is fine is already setup this way)

<img width="506" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/e3fe6a79-a374-4b98-9cc6-00a111cbfc58">

2023-09-12 22:04 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +          <ToggleButton
this is from the spreadsheet `Equiv. of the checkbox in D3.0` i think this is a good question for Tim.

2023-09-13 13:02 UTC, cagbakwu commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +          <ToggleButton
Yea it was. I spoke with him, I changed it to match

2023-09-13 14:32 UTC, cagbakwu commented on src/actions/bidderPortfolio.js
> +}
Added

2023-09-13 14:33 UTC, cagbakwu commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +    dispatch(bidderPortfolioDataSuccess(bidder));
added

2023-09-13 14:39 UTC, cagbakwu commented
@M00staff  This should be good to go.

2023-09-14 03:14 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +              'None Listed'
<img width="163" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/5c4ab55a-2804-4031-afe2-4ee408303775">

2023-09-14 03:16 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +            'None Listed'
<img width="163" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/9996ffa6-b368-4c79-9750-9b5fb0e4b57b">

2023-09-14 03:18 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatRow/BidderPortfolioStatRow.jsx
> +            <dt>Comments:</dt>
sorry - i meant to have the Emails still above `Comments` and below `Classifications`

2023-09-14 03:25 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +    dispatch(bidderPortfolioEditDataSuccess(clientData));
👍

2023-09-14 03:34 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +  const eligible = !included;
OK - so this is a little confusing for me... 

The way i understand it - the value for cusp/eligible bidder is going to come from the new endpoint (somehow)

Here, it looks like it's just defaulting to `cusp` and attached to the `included` value. 

If its the case that BOTH are true (that the value will come from the endpoint AND the toggle button changes that value) then this probably needs to be thought out a little bit more.   I'm not sure how, exactly though 🤔

2023-09-14 03:35 UTC, M00staff commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
> +  const eligible = !included;
it might be a problem for when we get to the API ticket ...

2023-09-14 03:45 UTC, M00staff commented on src/actions/bidderPortfolio.js
> +// }
did you mean to keep this in?

2023-09-14 03:47 UTC, M00staff commented on src/actions/bidderPortfolio.js
> +export function bidderPortfolioEditDataSuccess(client) {
Nit-pick ... naming

2023-09-14 03:49 UTC, M00staff commented
just a few tiny things
- move the email fields to above the comment field - but below classification
- fix that one lack of space after that colon
- commented code
- rename that action 

i'll take another look in the AM and maybe try to think through how that ribbon will work - this should be OK after that

2023-09-14 19:51 UTC, cagbakwu commented
> just a few tiny things
> 
> * move the email fields to above the comment field - but below classification ✅ 
> * fix that one lack of space after that colon  ✅ 
> * commented code ✅ 
> * rename that action ✅ 
> 
> i'll take another look in the AM and maybe try to think through how that ribbon will work - this should be OK after that

2023-09-15 03:17 UTC, M00staff approved these changes

2023-09-15 03:22 UTC, merged