Tm 4834 bureau exception list
MetaPhase-Consulting/State-TalentMAP pull request #2682
Opened 2023-09-06 16:31 UTC by cagbakwu

https://metaphase.atlassian.net/browse/TM-4834
-Added new Admin page: Bureau Exception Access
-Added a  list of bureau users 
-Added Edit button 
-Added a page for Bureau add/remove list.
<img width="1505" alt="Screenshot 2023-09-06 at 11 16 56 AM" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/41ab494d-9af0-4069-9015-ce6aa36a0ec8">
<img width="1505" alt="Screenshot 2023-09-06 at 11 19 56 AM" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/4b7df019-7b0b-4ae0-910f-89a9fd872048">

2023-09-07 00:07 UTC, M00staff commented
so, is this still a work in progress or good to be reviewed?

if it's still a WiP - then what is left to be done?

2023-09-07 00:13 UTC, M00staff commented
If you want someone to look over something specific - please comment it out in the PR.

2023-09-07 01:52 UTC, M00staff commented
Going forward - reach out to Tim before starting work on a ticket, and make sure you understand all of the asks.  

When wrapping up coding, reach out to him again - and do a screen share of what you have locally, so he can go over it with you, to make sure everything is there and looks right... that way we can spend more time reviewing the code, and less time making sure it works.

2023-09-11 17:42 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionListCard.jsx
> +            Bureau Access: {BureauNames.toString()}
add a space after the comma separation
<img width="203" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/a55e98ec-751a-4c24-88c3-c5ba139d2a38">

2023-09-11 17:44 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  const { isAO } = props;
So, I'm not sure if this prop needs to be here ... it looks like you pass it into the `<BureauExceptionListCard />` component, but then don't use it for anything?

![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/782ed029-fe4a-40b1-8a43-7667b5a7df3a)
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/3cc09d5d-79ca-4a11-a746-01918da542e8)

2023-09-11 17:49 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  const genericFilters = useSelector(state => state.filters);
why are you pulling in generic filters, when there are no filters to filter?

i think you need to be a little more targeted and precise in your copy pasting

2023-09-11 17:50 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  const genericFilters = useSelector(state => state.filters);
on top of that - turns out, with these new pages we don't even use the generic filters (at least not for any of the ones I've seen)

2023-09-11 18:02 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  };
yea - AFAIK, we aren't going to be getting pagination for any of the new pages ... so you can remove all the pagination related code. 

we'll probably have to add a scroll bar and maybe think through a solution for the load times

2023-09-11 18:05 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  const genericFilters = useSelector(state => state.filters);
we should probably have a filter for names 🤔

you could have the frontend handle it, based on the initial data fetch - i did something similar last night in my Bid Seasons API branch on this repo

2023-09-11 18:14 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  });
yea - so when you're copying stuff over at light speed, try to ask yourself `"what is this piece of code doing?"`

an example from the Search Post Access Page
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/0df3acca-dbda-4664-91c7-6ee9355e9bf8)
this bit is normally passed to the API to filter the results, so it calls another search, but with the results filtered ... 

but in your case - there are no filters... 

even if we add the ability to filter names on the frontend, i don't THINK you'll need this at all, and the dispatch function doesn't need an arg.

2023-09-11 18:23 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +    genericFiltersIsLoading ?
this is what originally caught my eye - we wait for the generic filters to load before rendering the page ... but, the filters aren't used for anything 😂

2023-09-11 18:23 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  isAO: PropTypes.bool,
but, why?

2023-09-11 18:34 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
> +  };
you could save the next guy some time by passing the action down to this component through its props (or however) and firing that action ... it'll prolly be a post request and the data object will have the ID of the user and the ID of the Bureau to add

2023-09-11 18:34 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
> +  };
was this a requirement?

2023-09-11 18:38 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
> +  };
i think the list of bureaus will be really, really long ... i removed it from the post access pages

2023-09-11 18:43 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
> +  ];
yea - so, I'm looking at the spreadsheet and this data is going to come from an endpoint. 

so, it needs that same Redux boilerplate and will be a simple get request.

2023-09-11 18:44 UTC, M00staff commented on src/actions/bureauException.js
> +});
yea - so the response from the new endpoint is gonna be different ... but, pretty much, no pagination and `results` will be called `data`

2023-09-11 18:47 UTC, M00staff commented on src/actions/bureauException.js
> +}
yea - so what selections are we saving here?

I'm doing the API stuff for the Bid Seasons page now, and noticed that there were a few Reducers & Actions that didn't do anything, and weren't used anywhere. 

i think there's a lot of the same thing here.

2023-09-11 18:49 UTC, M00staff commented on src/reducers/bureauException/bureauException.js
> +export function bureauExceptionsPositionSearch(state = [], action) {
what are we searching?

2023-09-11 18:57 UTC, M00staff requested changes
yea - so I know we are trying to move fast, and you're still ramping up, but please try to proofread your code before having anyone review it. 

there's a lot of un-necessary lines in here.

Try to understand what each line is doing, before adding it - that should also help when building out the other pages.

2023-09-12 15:52 UTC, cagbakwu commented
Making corrections 🚀

2023-09-12 21:54 UTC, cagbakwu commented on src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
> +  };
Yea its needed for the list of bureau codes, its currently in a scrollview.

2023-09-13 15:25 UTC, cagbakwu commented
@M00staff this should be good to go too.

2023-09-14 02:29 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +    fetchAndSet(false);
```suggestion
    fetchAndSet();
```

this function doesn't take any arguments ... you also prolly dont need to even abstract to its own function and can just fire the actions here

2023-09-14 02:34 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionListCard.jsx
> +  dispatch: () => {},
you dont really need to pass the dispatch through this component - you can import it at the top of the file

its does, however - need to be passed down to `<EditBureauExceptionList />` though (cause the way sweet alert works)

kind of a nit pick🤷

2023-09-14 02:35 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/EditBureauExceptionList.jsx
> +    dispatch(saveBureauExceptionSelections(bureauUser));
🙏

2023-09-14 02:52 UTC, M00staff approved these changes
OK - so this is all passable... a few little nit-picks, but this is good to go. 

Hopefully wont be too much of a pain to map the data we get back from the API to the structure you used 🤔

2023-09-14 02:53 UTC, M00staff commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionList.jsx
> +  };
still missing a scroll bar - add like 20 names to your list and you'll see...

could be the list we get back has like 300 names

2023-09-14 02:55 UTC, M00staff commented
also, try to be a little cognizant of the labels and what not you have on your PRs ... this one was still marked as WiP

2023-09-14 13:56 UTC, cagbakwu commented on src/Components/AdministratorPage/BureauExceptionList/BureauExceptionListCard.jsx
> +  dispatch: () => {},
ok ill remove it

2023-09-14 14:29 UTC, merged