[TM-4832] Cycle Job Category
MetaPhase-Consulting/State-TalentMAP pull request #2697
Opened 2023-09-13 18:12 UTC by jlam-mpc

Features:
- 

[TM-4832](https://metaphase.atlassian.net/browse/TM-4832)

2023-09-18 18:05 UTC, cagbakwu requested changes

2023-09-20 14:48 UTC, cagbakwu requested changes

2023-09-20 14:48 UTC, cagbakwu commented on src/Components/AdministratorPage/CycleJobCategory/CycleJobCategory.jsx
> +                            <p>New Job Category</p>
Maybe this could have some functionality of adding a row to the table. If the AC says nothing then disregard this.

2023-09-20 15:22 UTC, jlam-mpc commented on src/Components/AdministratorPage/CycleJobCategory/CycleJobCategory.jsx
> +                            <p>New Job Category</p>
This needs to be connected to Patrick's Job Categories feature I believe. Assignment Cycles, Cycle Job Categories, and Job Categories are all connected but separately developed so I need to make a follow up PR to bring them together and navigate them properly. Leave it alone for now basically!

2023-09-25 19:25 UTC, M00staff commented on src/actions/cycleJobCategories.js
> +          const randInt = Math.floor(Math.random() * 2);
👍

2023-09-25 19:30 UTC, M00staff approved these changes
this one is all pretty simple and straight forward - i'll go ahead and merge this in and throw it up on dev

2023-09-25 19:37 UTC, cagbakwu approved these changes
Looks good 👍

2023-09-25 19:55 UTC, merged