[TM-4915] Bidding Tool
MetaPhase-Consulting/State-TalentMAP pull request #2705
Opened 2023-09-20 06:08 UTC by jlam-mpc

Features:
- New `Bidding Functions` menu section
- New `Bidding Tool` feature
  - Browse a list of bidding tools
  - Create new bidding tool
  - View existing bidding tool
  - Edit existing bidding tool

Review Tips:
- Update feature flags config in db
- Ensure `Bidding Functions` and `Bidding Tool` exist in the menu and are accessible
- Ensure you can view list, redirect to add page, go back, redirect to details page, edit details, cancel edits
- Skim redux implementation in diff and make sure it is set up in a way that makes sense with the pending API work?
- Skim code changes for any alarmingly bad practices?

[TM-4915](https://metaphase.atlassian.net/browse/TM-4915)

2023-09-23 00:43 UTC, M00staff commented on src/Components/BiddingFunctionsPage/BiddingTool/BiddingTool.jsx
> +                    View / Edit
one of the A/C's are that Entry (whatever that is) and the Edit button are visible to the Admin only

seems like a pretty simple frontend thing to add - we do it elsewhere with a block that looks like
`const isSuperUser = !userHasPermissions(['superuser'], userProfile.permission_groups);`

2023-09-23 01:00 UTC, M00staff commented on src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
> +                key={shortid.generate()}
IIRC - when i first started, we were trying to use shortID in a similar way, and i was having issues with it 

this SO gives a simple reason why the `shortid.generate()` should at the very least be in the `sections` data and not here
https://stackoverflow.com/questions/54764139/set-react-keys-unique-by-using-shortid-generate-in-this-way

2023-09-23 01:06 UTC, M00staff commented on src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
> +      setEfmIssues(result?.efm_issues ?? '');
sweet use of nullish coalescing!  🙌

2023-09-23 01:14 UTC, M00staff commented on src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
> +            <button onClick={onCancel}>Submit</button>
this totally might be a me thing - but it's a little confusing when the word 'Submit' is used to answer the question "Are you sure?" 🤔

i noticed it in another page, as well - i think it'd be a little more clear if it was "Yes/No" 

.. more of a UX thing, tbh

2023-09-23 01:37 UTC, M00staff commented on src/Components/BiddingFunctionsPage/BiddingTool/BiddingTool.jsx
> +                  <Link to={appendedLocation() + d.id}>
so, I'm not sure what the issue is - or if its by design, but i just get a spinner when i click the `view/edit` link

<img width="353" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/2405a992-2e04-4f5b-b081-7dfeeec93db1">
<img width="1399" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/debf43b1-62fb-4862-94db-4fcb3bdb1cb9">

2023-09-23 01:42 UTC, M00staff commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +    ],
this change seems out of place?

2023-09-23 01:43 UTC, M00staff commented on src/Components/PositionExpandableContent/PositionExpandableContent.jsx
> +    if (editMode && form && !form.staticBody) return [];
also, this - maybe make a tiny separate PR for cleanup on position management stuff?

it'll get merged and approved quicker

2023-09-23 01:46 UTC, M00staff commented on src/Containers/BiddingFunctions/BiddingFunctions.jsx
> +  }
is there a reason you used the old class based component to stub this out?

they're getting phased out - functional components w/ hooks all the way

2023-09-23 01:51 UTC, M00staff commented on src/sass/_common.scss
> +    margin-bottom: 2px !important;
I'm not a stickler for CSS - but, it's generally bad practice to use the `!important` property

It's totally fine to use it - if you can't find a workaround, and end up spinning your wheels on it for too long

2023-09-23 01:55 UTC, M00staff commented on src/actions/biddingTool.js
> +    api().patch('biddingtool-ep/', data)
I think creating a new record in the DB would be a POST

2023-09-23 02:00 UTC, M00staff commented on src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
> +            <div>Edit</div>
ahhh - i see now!

disregard that other comment about the Admin & Edit stuff

2023-09-23 02:02 UTC, M00staff requested changes
a few tiny things - but the big one is not being able to get to the edit/view page.

might just be something wonky on my end 🤷

2023-09-26 14:06 UTC, jlam-mpc commented on src/Components/BiddingFunctionsPage/BiddingTool/BiddingToolCard/BiddingToolCard.jsx
> +            <button onClick={onCancel}>Submit</button>
I agree I will change it in this PR but we'd need to make a touch up pr to standardize it among other modals too.

2023-09-26 14:08 UTC, jlam-mpc commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> +    ],
It's to adapt to a PositionExpandableContent change I made. It accepts a new array object structure instead of the old way. If I revert this change, the edit mode would break on this card.

2023-09-26 14:13 UTC, jlam-mpc commented on src/Containers/BiddingFunctions/BiddingFunctions.jsx
> +  }
I made it based on the other page containers I reviewed. It's currently not being used- being left in in case post 9/30 we decide to make a separate Bidding Function menu category work out with more clear roles because I had a lot of back and forth with Tim Victoria and Elizabeth. I could remove these files or just leave them in case?

2023-09-26 14:36 UTC, M00staff commented on src/Containers/BiddingFunctions/BiddingFunctions.jsx
> +  }
if you want to leave it in - make it a functional component

2023-09-26 22:04 UTC, merged