TM-4846: Job Categories Save/Edit Integration
MetaPhase-Consulting/State-TalentMAP pull request #2708
Opened 2023-09-21 13:09 UTC by pveland621

Since we didn't really have a great mockup for this, I initially tried to handle it all on one page but due to the way that WS returns the skills data (can't just make an empty call for a list of all skills, have to send a category ID with it) I ended up just creating a quick modal to handle all create functionality and the base page handles edit functionality. 

Alternatively, if we're saying that we just want to make sure we get all the UI work cranked out, this is technically done for the UI portion, only FE changes needed are just the code to gather all the inputs and package them the way WS wants.

EDIT: per discussion, i will write down what's left to be done for the integration (closing out edit functionality) and create a ticket for post 9/30 work. this pr is just for having the UI up and ready for 9/30

Dual Merge: 
- [API PR](linkToAPIPR)
- [Mock PR](linkToMockPR)

[Ticket](https://metaphase.atlassian.net/browse/TM-4846)

2023-09-26 02:37 UTC, M00staff commented on src/Components/AdministratorPage/JobCategories/JobCategories.jsx
> +    setSelectedSkillIds([]);
so, there's something wonky going on with (I THINK) this logic. 

When i select a job category for the first time, it will auto check these (currently unchecked) job categories...

<img width="939" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/27c02ab9-a30d-43bf-ad62-267484308928">

Then if i flip the toggle to edit mode and uncheck them - and then hit `selectAll` - they won't check anymore, and you get the screen shot above.

Also, you can jimmy it in a way where `selectAll` is true, but not everything is selected

<img width="872" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/011b1957-47ec-4af4-a061-1981fcef6d75">

I think there's something off with how the job category selection auto checks the check boxes, and how the select all and checkboxes work, in general ... if that makes sense

2023-09-26 02:43 UTC, M00staff requested changes
If we're just going for the frontend portion of this - make sure all the check boxes are working correctly between selecting a Job Category and shifting to toggle mode and manually checking the boxes... 

TBH - I'm not exactly sure how this is all supposed to function - but, I am certain there is something amiss code-wise with these check boxes.

2023-09-26 19:18 UTC, pveland621 commented
@M00staff yup i saw it too, pushed a fix for it if you want to re-test

2023-09-27 01:09 UTC, M00staff approved these changes
Naturally, a lot of this will get re-worked for the integration - but it looks good, and is all working and clickable for a demo. 

Approving - though, there is a tiny merge conflict you gotta resolve, before you can merge 👍

2023-09-27 12:14 UTC, merged