TM-Cycle-Management/Assignment-Cycles
MetaPhase-Consulting/State-TalentMAP pull request #2717
Opened 2023-09-26 19:00 UTC by cagbakwu

Added the assignment cycle features from previously merged code to cycle management page.
https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/d93746fa-7955-47da-a993-9e510ea117b6

2023-09-26 21:24 UTC, cagbakwu commented
This is good to go. Its addition of code that was already merged 🚀

2023-09-26 21:35 UTC, M00staff commented
Fix this linting error - you need to install ESLint and pull in our rules... it will flag these for you
<img width="837" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/5f25d3d0-854f-435c-867f-60383f7daa78">

2023-09-26 21:41 UTC, M00staff commented
so question - what happens to the Assignment Cycle page that you created before?

this one?

https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2691

2023-09-26 22:07 UTC, cagbakwu commented
> so question - what happens to the Assignment Cycle page that you created before?
> 
> this one?
> 
> #2691

@M00staff  That page will no longer be in use.

2023-09-26 22:37 UTC, M00staff commented
@cagbakwu if the page isn't going to be in use - why keep it in the codebase..?

2023-09-27 02:13 UTC, M00staff commented on src/Constants/Menu.js
> -        } : null,
yea - so you're removing the link for the Assignment Cycles page, here - but all the code for it will still live in the codebase, and do nothing. 

https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2691/files

it'd prolly be simpler if you just reverted that whole PR - and while making for a larger diff - it'd prolly be better to do that as a part of this PR.

2023-09-27 02:24 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +                      </span>
i think one of the A/C's are that this only shows for Admins - so it needs that same `isSuperUser` logic wrapped around this button

2023-09-27 02:24 UTC, cagbakwu commented on src/Components/CycleManagement/CycleManagement.jsx
> +                      </span>
Ah yea true, adding it now

2023-09-27 02:42 UTC, M00staff commented
yea so, this styling leaves something to be desired - I'm not sure if there were any designs that came with this but... it doesn't look very good - and I'm generally not a sticker for styling

<img width="1858" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/22d33145-c737-4794-8a02-d2fed21df2b6">


I'm fairly certain that you did Ui for the Bid Seasons page - lets use that styling - with the modal pop-up 

(maybe with a little more padding on the sides  🤷)

<img width="2101" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/d996e856-24b5-47bd-b697-94cbc3d7e413">

2023-09-27 02:48 UTC, M00staff commented on src/Components/AdministratorPage/AdministratorPage.jsx
> -        <Route path="/profile/administrator/assignmentcycles" render={() => <AssignmentCycles />} />
yea - so if you just run through and delete all the code & files manually, it could get really sloppy - and odds are, that you'll miss something. 

just do a revert - and make a separate PR for it (now that I'm thinking about it) cause this one will just get massive and even harder to review

2023-09-27 02:50 UTC, cagbakwu commented on src/Constants/Menu.js
> -        } : null,
@M00staff  It wasn't much work since it wasn't linked to anything anymore so I just removed the folder and FFs.

2023-09-27 02:59 UTC, M00staff commented on src/Components/CycleManagement/CycleSearchCard.jsx
> +                <CheckBox
<img width="281" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/d04faa9a-62cb-4e08-a0e2-ec3bd413e334">

<img width="270" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/643de32e-54f8-4575-9c32-0863beaf9ffc">

2023-09-27 03:06 UTC, M00staff commented on src/Components/CycleManagement/CycleSearchCard.jsx
> +  };
this is a bit weird - A/C's say `Edit populates with existing Assignment Cycle data:` 

but, it doesn't look like any of the edit fields look the same as the data that are passed into the component 🤔

not sure how it's supposed to work - but regardless, just hardcoding the data here is wrong.. there is dummy data in the `cycleManagement` action that you can update and use.

2023-09-27 03:10 UTC, M00staff requested changes
yea - this is going to require a few pass throughs, but for now:

- Make a separate PR reverting the PR with all the dead code
- Change the styling so we're using modals for the edit & create instead of just opening up the cards
- Use the hardcoded data, action & reducers that were already setup for this component - and just expand on them.

2023-09-27 03:25 UTC, M00staff commented on src/Constants/Menu.js
> -        } : null,
These were all the files touched in that PR - I'm fairly certain you dont need those actions & reducers for starters. 

might be able to clean up a few other things as well

<img width="305" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/630c3110-6f09-47dd-856b-b6031f595017">

2023-09-27 11:59 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/dfcd7261-cb96-42ea-a59b-989ff3d196fe)
For the reverting PR - there is a handy GitHub feature that should make it pretty straightforward - Hit Revert on the PR you want to revert

2023-09-27 12:08 UTC, elizabeth-jimenez commented
> ![image](https://user-images.githubusercontent.com/23065001/270969531-dfcd7261-cb96-42ea-a59b-989ff3d196fe.png) For the reverting PR - there is a handy GitHub feature that should make it pretty straightforward - Hit Revert on the PR you want to revert

Just tried it, couldn't auto revert

2023-09-27 12:25 UTC, elizabeth-jimenez commented
It looks like you are now using Cycle Management styles, so you'll want to go ahead and remove or move these changes from ur old PR: https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2691/files#r1338524336 and https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2691/files#r1338524481

2023-09-27 12:28 UTC, elizabeth-jimenez commented
> yea so, this styling leaves something to be desired - I'm not sure if there were any designs that came with this but... it doesn't look very good - and I'm generally not a sticker for styling
> 
> <img alt="image" width="1858" src="https://user-images.githubusercontent.com/12723877/270844783-22d33145-c737-4794-8a02-d2fed21df2b6.png">
> I'm fairly certain that you did Ui for the Bid Seasons page - lets use that styling - with the modal pop-up
> 
> (maybe with a little more padding on the sides 🤷)
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/12723877/270845263-d996e856-24b5-47bd-b697-94cbc3d7e413.png">

Yea unfortunately, no designs - we def want to make sure we make it look how we think is best, but if that isn't your strong suit feel free to reach out to other team members to vet your ideas before opening it up for review

2023-09-27 12:31 UTC, cagbakwu commented on src/Components/CycleManagement/CycleSearchCard.jsx
> +                <CheckBox
Yes, this was cleared by Tim and also done everywhere else.

2023-09-27 20:18 UTC, cagbakwu commented
> yea - this is going to require a few pass throughs, but for now:
> 
> * ❌Make a separate PR reverting the PR with all the dead code - Could do but removed all old code and uses throughout app.
> * ✅ Change the styling so we're using modals for the edit & create instead of just opening up the cards
> * ✅ Use the hardcoded data, action & reducers that were already setup for this component - and just expand on them.

Also jeanies giving a second eye on the CSS positions of the edit table.

2023-09-27 20:32 UTC, cagbakwu commented on src/Constants/Menu.js
> -        } : null,
all gone 🚀

2023-09-27 21:10 UTC, elizabeth-jimenez commented
Revert Check:

- src/Components/AdministratorPage/AssignmentCycles/AssignmentCyclesCard.jsx was deleted
      - was this intentional? it had cycle job categories changes to it since the older PR

- src/Components/AdministratorPage/AssignmentCycles/NewAssignmentCycle.jsx
      - renamed and moved to src/Components/CycleManagement/EditAssignmentCycles.jsx
      - small text updates
      - useCycleJobCategories removals on this PR intentional?

- src/Constants/SystemMessages.js remained unchanged
       - which makes sense

- All other files cleanly reverted

2023-09-27 21:19 UTC, cagbakwu commented
> Revert Check:
> 
> * src/Components/AdministratorPage/AssignmentCycles/AssignmentCyclesCard.jsx was deleted
>   - ❓ was this intentional? it had cycle job categories changes to it since the older PR
> * src/Components/AdministratorPage/AssignmentCycles/NewAssignmentCycle.jsx
>   - ✅ renamed and moved to src/Components/CycleManagement/EditAssignmentCycles.jsx
>   - ✅ small text updates
>   - ❓useCycleJobCategories removals on this PR intentional?
> * src/Constants/SystemMessages.js remained unchanged
>   - ✅ which makes sense
> * ✅ All other files cleanly reverted

yep, that was meant to be deleted.
system Messages are meant to stay.
yep meant to remove useCycleJobCategories (edited) 





[4:18](https://metaphaseconsulting.slack.com/archives/C02UFQDBVAR/p1695849520314029)
everything is right :white_check_mark:

2023-09-28 04:11 UTC, M00staff commented
🤨
<img width="522" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/9ad15e23-a095-4b18-b208-0b0a59ddfdae">

2023-09-28 04:11 UTC, M00staff commented
clicked 'Edit'

<img width="720" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/5ee90b28-ba31-42c8-b438-c8440b0a5de5">

2023-09-28 04:21 UTC, M00staff commented
seems i cannot reproduce ^^ those bugs 

i still dont really like the way the edit looks 

<img width="1846" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/8d7ab2b3-adcd-464a-a687-c4fe2185b428">

but whatever, i'll take one more look in the AM

2023-09-28 13:29 UTC, cagbakwu commented
> seems i cannot reproduce ^^ those bugs
> 
> i still dont really like the way the edit looks
> 
> <img alt="image" width="1846" src="https://user-images.githubusercontent.com/12723877/271173400-8d7ab2b3-adcd-464a-a687-c4fe2185b428.png">
> but whatever, i'll take one more look in the AM

I think this is a better look.
![Screenshot 2023-09-28 at 8 21 45 AM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/e98de3c7-f26b-4770-8f39-394db296b99d)

2023-09-28 14:29 UTC, M00staff approved these changes

2023-09-28 14:34 UTC, merged