block existing bid season dates
MetaPhase-Consulting/State-TalentMAP pull request #2748
Opened 2023-10-20 15:25 UTC by elizabeth-jimenez

Disable the dates on the date pickers that already have a bid season attached to them.

~[API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/862)~

2023-10-20 15:26 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/EditBidSeasons.jsx
> +      }
i could instead grab the number of days between the two dates and then forEach on them, to get rid of the while loop, but `while` feels more natural for this scenario

2023-10-20 15:28 UTC, elizabeth-jimenez commented
Not very performant, so may not merge in - can keep here to play with optimization

2023-10-20 15:30 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/EditBidSeasons.jsx
> +    // remove current date range from bidSeasonDates$
may be able to pull this out to the parent and generate it once, feeding custom dates based on the bid season range

2023-10-20 15:33 UTC, elizabeth-jimenez commented
Scott noticed: they can still select a date before the start of a Bid Season all the way to after the end of that Bid Season - essentially completely engulfing a Bid Season

2023-10-27 17:07 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
> +const ManageBidSeasonsCard = ({ id, bidSeasonDateRanges, description, bidSeasonsBeginDate,
complaining about `id` not being used, even tho I do on L26

2023-11-03 00:55 UTC, M00staff commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
> +const ManageBidSeasonsCard = ({ id, bidSeasonDateRanges, description, bidSeasonsBeginDate,
if you change L26 to `id={id}` you can remove the linter complaint

2023-11-03 00:56 UTC, M00staff commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasons.jsx
> +          seasonDateInner?.beginDate === currentBeginDate ? [] : seasonDateInner?.dates);
The `.disableDates` will throw an error if `currentBeginDate` is null or undefined ... not sure yet why it's coming back that way

adding this logic in an if block fixes it - but i think there's something else off in this block

```
      if (currentBeginDate) {
        dateObj[currentBeginDate].disableDates =
          Object.values(dateObj).flatMap((seasonDateInner) =>
            seasonDateInner?.beginDate === currentBeginDate ? [] : seasonDateInner?.dates);
      }
```

<img width="782" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/04f29262-a415-473e-bb63-63c9af35468d">

2023-11-03 01:09 UTC, M00staff commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
> +            bidSeasonDateRanges[formatDate(bidSeasonsBeginDate)]?.disableDates}
something wonky going on here as well - anytime i click on 'edit' on any card - i get the same dates & data populating the modal...

<img width="491" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/2ad68813-e339-468d-bc74-c034804dc62d">

2023-11-03 01:35 UTC, M00staff requested changes
yea so this looks like a neat one to work on - but, a few things:

UX Stuff:
- when you open up 'add new bid season' - you just get entire months of un-pickable dates ... i think that might be super confusing for the user, especially without an error message or any kind of notification

- adding a button to change years on the datepicker would be nice for testing, but i dunno if that'd be useful to the user

- I can't tell that the disabled dates are disabled in Dark Mode

Code Stuff
- opening up the datepicker is really, really slow locally - i assume that lag would be much more pronounced in dev, and the other environments as well.  

- I think it's like you had mentioned - this logic is not very performant... it's also pretty gnarly to walk through and read.

- considering this logic is actually already handled in the database, I'm not sure why we would add it all a second time at such a big performance cost - when we can just expose the error message that comes back from the database, like we were doing - or at least just expand on that error handling logic

2023-11-03 13:24 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
> +const ManageBidSeasonsCard = ({ id, bidSeasonDateRanges, description, bidSeasonsBeginDate,
Ah thanks!

2023-11-03 14:35 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
> +            bidSeasonDateRanges[formatDate(bidSeasonsBeginDate)]?.disableDates}
Unix epoch! Looks like it isnt receiving dates at all and i think i know why 😭

2023-11-07 17:51 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasons.jsx
> +          seasonDateInner?.beginDate === currentBeginDate ? [] : seasonDateInner?.dates);
ugh so this is similar to the Agenda Item Validator error - after it was all working, i must have moved this line up `    dateObj.allDates = Object.values(dateObj).flatMap(({ dates }) => dates);` which broke it. Basically that loop expects to do the same modifications on the whole obj (and expects the same structure), but allDates deviates from all the other objs and doesn't need to be modified in that loop

2023-11-07 17:53 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasons.jsx
> +          seasonDateInner?.beginDate === currentBeginDate ? [] : seasonDateInner?.dates);
was messing around with Object.seal and Object.freeze, but couldnt find a good use case to freeze top keys/values only

2023-11-07 17:56 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageBidSeasons/ManageBidSeasonsCard.jsx
> +            bidSeasonDateRanges[formatDate(bidSeasonsBeginDate)]?.disableDates}
This is an error im realizing i make quite often and it's so sneaky! ur suggestion for id made me realize it. This was the fix 

```
          description={description}
          bidSeasonsBeginDate={bidSeasonsBeginDate}
          bidSeasonsEndDate={bidSeasonsEndDate}
          bidSeasonsPanelCutoff={bidSeasonsPanelCutoff}
          bidSeasonsFutureVacancy={bidSeasonsFutureVacancy}
          ```

2023-11-07 20:34 UTC, elizabeth-jimenez commented
"UX Stuff:

when you open up 'add new bid season' - you just get entire months of un-pickable dates ... i think that might be super confusing for the user, especially without an error message or any kind of notification" Yea, meant to add an alert letting them know - added it, but left it more generic so it is ready to go after I delete all the disable dates stuff

"adding a button to change years on the datepicker would be nice for testing, but i dunno if that'd be useful to the user" oh good find - i didnt even notice we didnt have it, i know some of our date pickers do. Agreed, in this case i dont think it'd be useful.

"I can't tell that the disabled dates are disabled in Dark Mode" Oof! Nice catch

"Code Stuff

opening up the datepicker is really, really slow locally - i assume that lag would be much more pronounced in dev, and the other environments as well." Yea, I assume too 😬 

"I think it's like you had mentioned - this logic is not very performant... it's also pretty gnarly to walk through and read."
It is performant, like by the time u hit Edit it is all done, the lag is the library we use, so just wanted to get this to a place where we MAY be able to use it in the future after consolidating our date pickers (but im still going to delete it before we merge this cause i can just come back to this PR if we ever do)

"considering this logic is actually already handled in the database, I'm not sure why we would add it all a second time at such a big performance cost - when we can just expose the error message that comes back from the database, like we were doing - or at least just expand on that error handling logic" I think with another library this would be doable, just unfortunately not this one. The main thing i was trying to get away from is exposing all error messages to users without vetting them first. So I pushed a PR for the API to handle that and also added an alert to let users know they will get an error if it overlaps, before they ever make the call.

2023-11-07 22:13 UTC, M00staff commented
yea - so the logic for all of this works... 

I'm curious though - how would the consolidating date picker ticket actually make this work better, if the library is the issue?

My understanding was - that ticket will have us create a 'shell' component that the existing DatePicker would live in, just so we can pass in props easier (which might not be entirely necessary, come to think of it 🤔) - not to create our own DatePicker, or pull in a different library to replace all the existing uses.

2023-11-08 12:35 UTC, elizabeth-jimenez commented
> yea - so the logic for all of this works...
> 
> I'm curious though - how would the consolidating date picker ticket actually make this work better, if the library is the issue?
> 
> My understanding was - that ticket will have us create a 'shell' component that the existing DatePicker would live in, just so we can pass in props easier (which might not be entirely necessary, come to think of it 🤔) - not to create our own DatePicker, or pull in a different library to replace all the existing uses.

Cause we may consolidate our Date Pickers to one that works better with date disabling. We have about 3 different Date libraries we are using throughout TM and many more custom stylings strewn about for them - and every time someone has to work on implementing a date picker, it feels like a styling nightmare. "pull in a different library to replace all the existing uses" this is likely. That ticket is to standardize our Date stylings both for existing components and make it easier for future uses

2023-11-08 14:15 UTC, M00staff commented
then we're definitely going to have to kick up the points on that ticket 🤔 ... by A LOT

2023-11-08 17:14 UTC, closed without merging