TM-4988 custom date picker
MetaPhase-Consulting/State-TalentMAP pull request #2765
Opened 2023-11-17 04:42 UTC by M00staff

Panel Meeting Date Range Picker now...
<img width="331" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/9d1b4e15-9196-45af-9c30-141dc7ab2f9f">
<img width="449" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/a0802af9-95db-4035-aee9-b7e7747a4c32">

[Ticket](https://metaphase.atlassian.net/browse/TM-4988)

Usage simple example in Projected Vacancy
```
          <TMDatePicker
            selected={overrideTED}
            onChange={setOverrideTED}
            wrapperClassName="panel-meeting date-wrapper-react larger-date-picker"
            icon={<FA name="fa fa-calendar" onClick={() => openDatePicker()} />}
            placeholderText={'MM/DD/YYY'}
            showIcon
            isClearable
          />
```

will render like this compared to current Date Picker used in Projected Vacancies 
(without any CSS changes - though it would require some - this is just a simple example)

<img width="391" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/c005b255-cb93-4bc0-a3b9-64377fe9fe19">

DOCS: https://reactdatepicker.com/ 

NOTE: We should be able to use this for every date input around the site with only slight tweaks to the passed in CSS classes 
- EXCEPT, i don't think it will work perfectly for blocking out dates for Bid Seasons - you can disable individual dates, by passing them in with the `excludeDates` prop (https://reactdatepicker.com/#example-date-range-for-one-datepicker-with-disabled-dates-highlighted) - recommended, but will still be able to select that range - we'd still just have the error be thrown after selecting a range with disabled dates, but at least they'd be visible
- OR you can only allow a max/min date, that will not allow any dates to be selected before the min date & after the max date (https://reactdatepicker.com/#example-date-range-with-disabled-navigation-shown)

2023-11-17 04:46 UTC, M00staff commented on src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
> +  const [selectedPanelMeetDate, setSelectedPanelMeetDate] = useState(get(userSelections, 'selectedPanelMeetDate') || [null, null]);
if using as a Date Range Picker - the default value passed down needs to be `[null, null]` so this block doesn't crash
```
          startDate={selectsRange ? value[0] : null}
          endDate={selectsRange ? value[1] : null}
```

2023-11-17 04:52 UTC, M00staff commented on src/Components/TMDatePicker/TMDatePicker.jsx
> +        {showIcon && icon}
might not need the `showIcon` prop - also - I couldn't get it working through the DatePicker itself for some reason .. docs have it working like 
<img width="791" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/45f2c67c-96a4-4824-a49e-114052108bf8">

or like 

<img width="787" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/109ba2f6-4ac4-4c6e-8ede-1bb1f28d987c">

tried a few different ways, and just settled on rendering the icon in the markup, instead of having the component do it 🤷

https://reactdatepicker.com/#example-calendar-icon
https://reactdatepicker.com/#example-calendar-icon-using-external-lib

2023-11-17 04:52 UTC, M00staff commented on src/Components/TMDatePicker/TMDatePicker.jsx
> +  excludeDates: PropTypes.arrayOf(PropTypes.instanceOf(Date)),
there are a slew of other props we can add as needed

https://reactdatepicker.com/

2023-11-17 04:53 UTC, M00staff commented on src/sass/_datePicker.scss
> +}
i figure most uses will need their own CSS rules that will look kind of similar

2023-11-21 20:53 UTC, jlam-mpc requested changes

2023-11-21 20:53 UTC, jlam-mpc commented on src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
> +  const [selectedPanelMeetDate, setSelectedPanelMeetDate] = useState(get(userSelections, 'selectedPanelMeetDate') || [null, null]);
Nice catch~

2023-11-21 20:53 UTC, jlam-mpc commented on src/Components/TMDatePicker/TMDatePicker.jsx
> +  icon: <></>,
I would add the calendar icon as the default icon so that you wouldn't need to specify icon every time you declare showIcon.

2023-11-21 20:53 UTC, jlam-mpc commented on src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
> +                wrapperClassName="panel-meeting larger-date-picker"
I almost want to suggest making the styles you chose as the default styles ingrained in the TMDatePicker component itself and then use this props for any additional specific classnames to append onto these.

Like, in TMDatePicker, you do 

<div className={`tm-daterange-wrapper ${wrapperClassName}`}>

and the scss file just has tm-daterange-wrapper as the uniform styling class and then to change anything specific you do panel-meeting and reach into the tm-daterange-wrapper className (which you'll probably not need to).

2023-11-21 20:53 UTC, jlam-mpc commented on src/Components/TMDatePicker/TMDatePicker.jsx
> +      <div className={`tm-daterange-wrapper-${wrapperClassName}`}>
See suggestion left on line 245 of PanelMeetingSearch

2023-11-21 20:53 UTC, jlam-mpc commented on src/sass/_datePicker.scss
> +  }
A little nitpicky of me but I would recommend you replace 147-149 with this

```
  .react-datepicker__close-icon {
    padding: 0px;
    margin: 0px 5px 0px 0px;

    &::after {
      line-height: unset;
    }
    &:hover {
      background-color: transparent !important;
    }
  }
```

2023-11-22 00:10 UTC, M00staff commented on src/Components/Panel/PanelMeetingSearch/PanelMeetingSearch.jsx
> +                wrapperClassName="panel-meeting larger-date-picker"
i think I'm following - swapped it so that the passed in classNames are just additional (though i kept the ability to pass in a className for either the wrapper or the component itself - just for added specificity, which I'm now using in this instance) 

and we're DEFINITELY going to be passing custom CSS classes into this component often, if the plan is to swap all of the existing date pickers.

2023-11-22 00:14 UTC, M00staff commented on src/sass/_datePicker.scss
> +  }
i think you mean through 159?

regardless - consolidated it all to 

```
  .react-datepicker__close-icon {
    padding: 0px;
    margin: 0px 5px 0px 0px;
    &::after {
      font-size: 20px;
      color: $alert-red;
      line-height: unset;
      background-color: transparent;
    }
    &:hover {
      background-color: transparent;
    }
  }
```

... no need for the `!important` tag this way

2023-11-24 22:06 UTC, jlam-mpc approved these changes

2023-11-27 14:58 UTC, merged