TM-5219, TM-5292, add DETO/RWA field to pub positions & position search
MetaPhase-Consulting/State-TalentMAP pull request #2802
Opened 2023-12-27 00:10 UTC by M00staff

The assumption here is that when we get the WS endpoint - we will call it in the API code and add it to the responses for `publishable_positions`, `available_positions` and `projected_vacancies` 

I think we do something similar for agenda items (mix the return for multiple WS endpoints into a single endpoint for our frontend)

[Ticket](https://metaphase.atlassian.net/browse/TM-5292)
[Ticket](https://metaphase.atlassian.net/browse/TM-5219)

2024-01-31 13:53 UTC, jlam-mpc reviewed
Everything looks good locally and I just had a few questions throughout the code diff. Will approve it shortly once it's been read through!

2024-01-31 13:53 UTC, jlam-mpc commented on public/config/config.json
> +    "deto_rwa": true,
What's the difference between the `deto_rwa` flag and the `deto` flag? Shouldn't all handling of deto be ff'ed in one flag?

2024-01-31 13:53 UTC, jlam-mpc commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +                    value={data?.deto_rwa || false}
If this comes back as a boolean shouldn't you just leave it as `data?.deto_rwa` for simplicity? It may also come back from the WS endpoints as Y/N or T/F as letters but I assume our backend might want to handle having it come in as a boolean.

2024-01-31 13:53 UTC, jlam-mpc commented on src/reducers/filters/filters.js
> +        ],
Looks good to me

2024-01-31 13:53 UTC, jlam-mpc commented on src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
> +    if (DETO_RWA_FLAG) {
In some components you check for `if (!DETO_RWA_FLAG)` and then pop/delete/remove while this one you check `if (DETO_RWA_FLAG)` and add the fields. I for some reason want to suggest that all of them use the same construct as this one because I wouldn't add anything to a const until I first know that permissions/feature flags are valid first (instead of adding the fields and then removing them if the code later discovers it is flagged off or they don't have permissions). 

Does that make sense? For some super duper minor sense of security sake?

2024-01-31 13:54 UTC, jlam-mpc commented
I forgot to add this comment but for this [ticket](https://metaphase.atlassian.net/browse/TM-5219) did you make sure if the code changes needed here need to be feature flagged in `deto_rwa` as well?

2024-02-02 04:26 UTC, M00staff commented on public/config/config.json
> +    "deto_rwa": true,
i THINK this original `deto` flag was added before we fully understood what the field/ask was ... it's attached to 2 pages `AssignmentCard` and `CyclePositionCard` - i think these are 2 newer pages, and it might be that we can remove old logic and FF. 

I'll need to double check.

2024-02-02 04:33 UTC, M00staff commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +                    value={data?.deto_rwa || false}
nice!

for some reason i thought if it returned undefined, it wouldn't work 😅

2024-02-02 04:40 UTC, M00staff commented on src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
> +    if (DETO_RWA_FLAG) {
🤷

updated!

2024-02-02 15:55 UTC, M00staff commented on public/config/config.json
> +    "deto_rwa": true,
got confirmation with tim - the DETO/RWA stuff should be relegated to just these two screens - we can add it back in with ease if that turns out to not be the case.

so - removed all the old deto stuff!

2024-02-02 16:06 UTC, M00staff commented on src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
> +    if (DETO_RWA_FLAG) {
actually, this does make sense - checking for not would trigger the code even if someone didn't add the flag on their UI

2024-02-02 16:46 UTC, M00staff commented
> I forgot to add this comment but for this [ticket](https://metaphase.atlassian.net/browse/TM-5219) did you make sure if the code changes needed here need to be feature flagged in `deto_rwa` as well?

yes - in `Search FiltersContainer` and `ResultsCard`

2024-02-02 22:04 UTC, elizabeth-jimenez commented on src/Components/PositionDetailsItem/PositionDetailsItem.jsx
> +const DETO_RWA_FLAG = () => checkFlag('flags.deto_rwa');
🙌

2024-02-05 18:00 UTC, elizabeth-jimenez commented on src/Components/Assignments/AssignmentCard/AssignmentCard.jsx
> -  if (!showDeto) {
we can delete line 116 too

2024-02-05 18:02 UTC, elizabeth-jimenez commented on src/Components/CyclePositionCard/CyclePositionCard.jsx
> -      { '': <CheckBox id="deto" label="DETO" value disabled /> },
there's also one in `staticBody`

2024-02-05 18:25 UTC, elizabeth-jimenez commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +                <Tooltip title="Eligibility can be modified in GEMS, contact your HRO to make changes.">
I really like the tooltip idea. I have a feeling they may ask for the little info icon to trigger it instead, especially since the disabled checkbox isn't super obviously disabled when the other one is checked, but let's see if they don't 🤞

2024-02-05 18:32 UTC, elizabeth-jimenez commented on src/Components/SearchFilters/SearchFiltersContainer/SearchFiltersContainer.jsx
> +      multiSelectFilterNamesTandem2.push('deto-rwa-tandem');
let's change these to camelCase, like the rest

2024-02-05 18:53 UTC, elizabeth-jimenez commented
Flip flag and check that hidden:
- [x] Position details
- [x] Publishable positions
- [x] Publishable positions form
- [x] Results card
- [x] Search filters

2024-02-05 18:56 UTC, elizabeth-jimenez requested changes
1. delete comment about deto in AssignmentCard.jsx
2. delete Deto in CyclePositionCard.jsx staticBdody
3. camelCase in SearchFiltersContainer.jsx

2024-02-05 18:56 UTC, elizabeth-jimenez commented
minor changes but g2g otherwise!

2024-02-06 15:23 UTC, elizabeth-jimenez approved these changes
🤌

2024-02-07 15:30 UTC, merged