[TM-4542] Employee Profile
MetaPhase-Consulting/State-TalentMAP pull request #2803
Opened 2024-01-02 14:43 UTC by jlam-mpc

[TM-4542](https://metaphase.atlassian.net/browse/TM-4542)

2024-01-03 16:40 UTC, cagbakwu requested changes

2024-01-03 17:52 UTC, M00staff commented on src/Components/ProfileDashboard/UserProfile/UserProfile.jsx
>          showEmployeeProfileLinks={showEmployeeProfileLinks}
I think the ticket is calling for an update to the public profile view of another user - not the user's own dashboard

so, the link would look like `http://localhost:3000/profile/public/8364589` 

that being said - I'm not sure how to test this locally since i keep getting `user not found` when trying to look up a user
<img width="344" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/95468289-1d24-41b5-942c-3a9e1c8667f3">

2024-01-03 18:54 UTC, elizabeth-jimenez commented
I think this may require both API and WS changes. I think right now both reports are only exposed to CDA

2024-01-03 19:43 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
> +    api().get(`/fsbid/employee/${hruId}/employee_profile_report/?redacted_report=${showRedactedProfilePreview ? 'true' : 'false'}`,
I think this can be shortened to `api().get(`/fsbid/employee/${hruId}/employee_profile_report/?redacted_report=${showRedactedProfilePreview}`,`

2024-01-03 19:52 UTC, elizabeth-jimenez commented on src/Components/ProfileDashboard/UserProfile/UserProfileGeneralInformation/EmployeeProfileLink.jsx
> +  showRedactedProfilePreview: false,
Let's set the prop to isRequired and make sure to explicitly pass the false along to all roles

2024-01-03 19:57 UTC, elizabeth-jimenez commented on src/Containers/ProfilePublic/ProfilePublic.jsx
> +          showRedactedProfilePreview: true,
related to comment https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2803/files#r1440875465, Line 55. What we show for which profiles can very quickly get outta hand and very confusing, so now we make the props explicit, in hopes of being more intentional for each role.

Another documentation thing i think will be great to add is an explanation of what happens when showRedactedProfilePreview is true: preview and download will be the same redacted report. But idk if that is better as a comment in this file? or where we render the pdf 🤔

2024-01-03 20:01 UTC, elizabeth-jimenez requested changes
1. prop to isRequired
2. showRedactedProfilePreview is true comment

2024-01-03 20:05 UTC, elizabeth-jimenez commented
Ticket is good-to-go from a FE perspective, just two small changes requested on PR. 
Hold off on merge until WS and API updates are ready too or after Release 12.0 branch up.

2024-01-03 20:05 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/156966b0-3ab5-401f-b6ac-64b7ce8325e1)
was just dismissing earlier Requested Changes

2024-01-16 10:38 UTC, jlam-mpc commented on src/Containers/ProfilePublic/ProfilePublic.jsx
> +          showRedactedProfilePreview: true,
Your reasoning makes a lot of sense. I'm not opposed to making the prop required at all I do see why we should explicitly declare them now that I'm rereading this component.

2024-01-16 11:13 UTC, jlam-mpc commented
> Ticket is good-to-go from a FE perspective, just two small changes requested on PR. Hold off on merge until WS and API updates are ready too or after Release 12.0 branch up.

Should I also be adding "Client Profiles" to the Bureau and Post sections of the sidebar features?

2024-01-16 14:57 UTC, elizabeth-jimenez commented
> > Ticket is good-to-go from a FE perspective, just two small changes requested on PR. Hold off on merge until WS and API updates are ready too or after Release 12.0 branch up.
> 
> Should I also be adding "Client Profiles" to the Bureau and Post sections of the sidebar features?

No, just exposing the report links is good :)

2024-01-30 13:43 UTC, elizabeth-jimenez approved these changes

2024-02-05 14:36 UTC, elizabeth-jimenez approved these changes

2024-02-05 14:37 UTC, merged