TM-4917: Manage EL Positions Integration
MetaPhase-Consulting/State-TalentMAP pull request #2854
Opened 2024-02-13 14:15 UTC by pveland621

Manage EL Positions Integration

Dual Merge: 
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/935)

[Ticket](https://metaphase.atlassian.net/browse/TM-4917)

2024-02-26 21:17 UTC, elizabeth-jimenez commented on src/reducers/entryLevel/entryLevel.js
> +export function entryLevelPositions(state = [], action) {
🙌

2024-02-26 21:21 UTC, elizabeth-jimenez commented on src/actions/entryLevel.js
> +    if (cancelELdata) { cancelELdata('cancel'); dispatch(entryLevelFetchDataLoading(true)); }
so moose questioned if this was needed, in another PR and after deep diving, turns out we don't 🙌 cause the whole function gets called again on a cancel, so this is redundant with L107 - checkout the updated patten in Publishable Positions. There is also an update to the catching of the err

2024-02-26 21:25 UTC, elizabeth-jimenez commented on src/Components/PositionExpandableContent/PositionExpandableContent.jsx
> +            <Row fluid className={`position-content--section position-content--details ${isCondensed ? 'condensed' : ''}`}>
what's `condensed` for?

2024-02-27 15:30 UTC, pveland621 commented on src/Components/PositionExpandableContent/PositionExpandableContent.jsx
> +            <Row fluid className={`position-content--section position-content--details ${isCondensed ? 'condensed' : ''}`}>
mockups and AC technically specify the un-expanded view of position cards to include all four of the checkboxes + MC end date

2024-02-27 15:40 UTC, elizabeth-jimenez commented on src/Components/PositionExpandableContent/PositionExpandableContent.jsx
> +            <Row fluid className={`position-content--section position-content--details ${isCondensed ? 'condensed' : ''}`}>
i think i may be seeing the same content w.o. condensed?

2024-02-27 15:53 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageEntryLevel/ManageEntryLevel.jsx
> +  const isLoading = elPositionsIsLoading || elFiltersIsLoading;
optional - track these individually so that the whole page doesn't reload on selection of a filter

2024-02-27 15:57 UTC, elizabeth-jimenez commented
We'll definitely want to lock down the Edit to one card at a time - for 12.1 tho, since they do want to release this and since the Editing functionality isn't there, let's lock down all the Edit ability by disabling those links

2024-02-27 17:39 UTC, elizabeth-jimenez requested changes
1. update cancel pattern
2. isCondensed needed?
3. make filter loading state independent of card loading - optional
4. lock down Edit ability for 12.1

2024-02-27 19:01 UTC, pveland621 commented on src/Components/PositionExpandableContent/PositionExpandableContent.jsx
> +            <Row fluid className={`position-content--section position-content--details ${isCondensed ? 'condensed' : ''}`}>
<img width="1475" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/31417027/dbd43721-aeef-438e-b450-8702d9058521">

this is without condensed, it's on two lines and the mockup only has them on 1 line - not opposed to taking out condensed, was just trying to match mockup

2024-02-27 21:21 UTC, elizabeth-jimenez commented
@pveland621 locked down Edit ability?

2024-02-28 14:58 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageEntryLevel/ManageEntryLevel.jsx
> +      {!isLoading &&
i think you'll still want a spinner tho if it is loading

2024-02-28 14:59 UTC, elizabeth-jimenez commented on src/Components/AdministratorPage/ManageEntryLevel/ManageEntryLevel.jsx
> +  const isLoading = elPositionsIsLoading || elFiltersIsLoading;
you weren't 🙌  it just looked like u were

2024-02-28 15:01 UTC, elizabeth-jimenez commented on src/Components/PositionExpandableContent/PositionExpandableContent.jsx
> +            <Row fluid className={`position-content--section position-content--details ${isCondensed ? 'condensed' : ''}`}>
oh i see, i did see that. Yea i wouldnt worry about matching mockups that closely, as they dont provide guidance on diff screen sizes

2024-02-28 15:10 UTC, elizabeth-jimenez commented
Verifying
1. update cancel pattern - still needed for entryLevelFiltersFetchData
2. isCondensed needed? - intentional, no changes needed
3. make filter loading state independent of card loading - optional - implemented, but need spinner for non-filters too
4. lock down Edit ability for 12.1 - locked down, but not gray

2024-02-28 16:10 UTC, elizabeth-jimenez approved these changes

2024-02-28 16:12 UTC, merged