[TM-5389] Projected Vacancy Integration (Edit)
MetaPhase-Consulting/State-TalentMAP pull request #2861
Opened 2024-02-14 13:53 UTC by jlam-mpc

Dual Merge: 
- [API PR](linkToAPIPR)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/437)

[TM-5389](https://metaphase.atlassian.net/browse/TM-5389)

2024-02-22 16:02 UTC, elizabeth-jimenez commented
Update to use new Edit redux pattern, if possible

2024-02-22 19:45 UTC, elizabeth-jimenez commented on src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
> +    dispatch(projectedVacancyLanguageOffsets({ positon_seq_num: result?.position_seq_num }));
not seeing this being captured over in the action

2024-02-22 19:45 UTC, elizabeth-jimenez commented on src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
> +    dispatch(projectedVacancyLanguageOffsets({ positon_seq_num: result?.position_seq_num }));
by this i mean the argument

2024-02-22 19:46 UTC, elizabeth-jimenez commented on src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
> +    dispatch(projectedVacancyLanguageOffsets({ positon_seq_num: result?.position_seq_num }));
comment applies to both `projectedVacancyMetadata` and `projectedVacancyLanguageOffsets`

2024-02-22 19:46 UTC, elizabeth-jimenez commented on src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
> +    dispatch(projectedVacancyLanguageOffsets({ positon_seq_num: result?.position_seq_num }));
i wonder how the cancel is going to play with multiple calls tho 🤔

2024-02-23 16:42 UTC, elizabeth-jimenez commented
I wonder if we should break out the   `const isLoading = filtersLoading || positionsLoading || languageOffsetsLoading;` to be filter agnostic and track the filter loading separately; that way the whole page doesn't blink on selection of a filter

2024-02-23 16:45 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/4d3a1247-b555-4da0-a97e-8f411d13b03a)
👀

2024-02-23 17:31 UTC, elizabeth-jimenez commented on src/Components/ProjectedVacancyCard/ProjectedVacancyCard.jsx
> +import { formatDateFromStr, getDifferentials } from 'utilities';
```suggestion
import { formatDate, getDifferentials } from 'utilities';
```

2024-02-23 17:44 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/fb637a1e-70cf-4816-93a6-075afad43cf1)
to Languages and maybe not show if they don't have?

2024-02-23 18:56 UTC, elizabeth-jimenez commented
> ![image](https://private-user-images.githubusercontent.com/23065001/307406485-fb637a1e-70cf-4816-93a6-075afad43cf1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTA1OTAsIm5iZiI6MTcwODcxMDI5MCwicGF0aCI6Ii8yMzA2NTAwMS8zMDc0MDY0ODUtZmI2MzdhMWUtNzBjZi00ODE2LTkzYTYtMDc1YWZhZDQzY2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDE3NDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTZjMGM5ZGFiMjM3NzhkMTg5MWVkNDM0OWIwZmIxZGYwZWEyMGZmMDQ1ZjcyNzk3MDhkNmI1YTk0OTQ1ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J6SgFKcaByKzCqj45-8UP-2zWCyoFiBBkYsOK6KjS1A) to Languages and maybe not show if they don't have?

i created a [function](https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2879) we can use for this :)

2024-02-23 18:59 UTC, elizabeth-jimenez commented on src/actions/projectedVacancy.js
> +          });
slightly new cancel pattern removes this, as it is redundant with the one on L268, 269 - checkout Publishable Positions for new pattern

2024-02-23 19:31 UTC, elizabeth-jimenez requested changes
1. break out loading for filters - optional
2. Date Formatting
3. Incumbent TED discrepancy
4. Language to plural
5. Languages formatting. Check function in new PR
6. Slight updates to Cancel pattern

2024-02-28 15:43 UTC, scott062 commented
Nice job Jeanie - I think there's a lot more requirement, as you noted, that we need to get clarification on, but I think this is at a workable stopping point and FE and BE are interacting nicely.

2024-02-28 15:45 UTC, elizabeth-jimenez approved these changes

2024-02-28 16:31 UTC, merged