TM-5563: Combining Pay Plan and Grade on Agendas
MetaPhase-Consulting/State-TalentMAP pull request #2866
Opened 2024-02-20 15:21 UTC by pveland621

ACs:
Verify combined field is showing up and grade field is removed on:
1. agenda item maintenance
2. panel agenda item
3. print view of panel meeting agenda 
4. agenda item history

Dual Merge: 
- [API PR](linkToAPIPR)

[Ticket](https://metaphase.atlassian.net/browse/TM-5563)

2024-02-26 16:56 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/76744a80-cd38-4868-b0fa-013f734794a2)

2024-02-26 16:56 UTC, elizabeth-jimenez requested changes
1. in _variables.scss go through the 6 configs for Agenda Item Maintenance Legs and update, as needed.
2. in AgendaLeg.jsx update onHover$()

2024-02-26 16:59 UTC, elizabeth-jimenez commented on src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
> +      content: (<div>{`${get(leg, 'pay_plan') || defaultSepText || '--'} ${defaultSepText || leg?.grade || '--'}`}</div>),
`combined_pp_grade`?

2024-02-26 17:07 UTC, elizabeth-jimenez commented on src/Components/Agenda/AgendaLeg/AgendaLeg.jsx
> +      content: (<div>{`${get(leg, 'pay_plan') || defaultSepText || '--'} ${defaultSepText || leg?.grade || '--'}`}</div>),
```suggestion
      content: (<div>{`defaultSepText || ${get(leg, 'combined_pp_grade') || DEFAULT_TEXT}`}</div>),
```

this should cover it

2024-02-26 17:17 UTC, elizabeth-jimenez commented
Re-verify these after updates

- [ ] agenda item maintenance read
- [ ] AIM edit
- [ ] panel agenda item
- [ ] print view of panel meeting agenda
- [ ] agenda item history

2024-02-27 18:48 UTC, pveland621 commented
- [x] agenda item maintenance read
- [x] AIM edit
- [x] panel agenda item
- [x] print view of panel meeting agenda
- [x] agenda item history

took me waaaaaay too long to find where PMA's exclude arrow row styling came from but i'm 99% sure i covered everything now

2024-02-27 21:01 UTC, elizabeth-jimenez commented on src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
> +    'Location/Org',
wat are you doing to me 😭

2024-02-27 21:02 UTC, elizabeth-jimenez commented on src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
> +    'Location/Org',
i intentionally added that space cause it was overflowing with it - but i did notice today that i didnt account for some css changes, but all good, i'll do it after you and Charles merge y'all work, to avoid conflicts

2024-02-27 21:08 UTC, elizabeth-jimenez commented on src/sass/_variables.scss
>    "Org": 4,
Grade removed and everything beneath Grade's previous location decreased by 1 💅 🎊

2024-02-27 21:09 UTC, elizabeth-jimenez approved these changes

2024-02-27 21:16 UTC, pveland621 commented on src/Components/Agenda/AgendaItemLegsForm/AgendaItemLegsForm.jsx
> +    'Location/Org',
i am so sorry!

2024-02-28 14:36 UTC, merged