TM-5602-Action
MetaPhase-Consulting/State-TalentMAP pull request #2872
Opened 2024-02-21 20:44 UTC by cagbakwu

[Ticket](https://metaphase.atlassian.net/browse/TM-5602)
![Screenshot 2024-02-21 at 2 42 12 PM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/1bc7d480-cd9e-46e4-9fc9-922af05ec08d)
![Screenshot 2024-02-21 at 2 42 53 PM](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/135657303/591330d1-86e6-47f8-9484-0338591ab1c3)

2024-02-22 19:18 UTC, cagbakwu commented
Only 4 files, the other 4 are snapshots.

2024-02-22 20:59 UTC, elizabeth-jimenez commented
We have some CSS that's specific to which row is where that you'll definitely want to update, as well

2024-02-22 20:59 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/de90d266-56f7-4ed7-b98b-606b6f42e44f)

2024-02-22 21:05 UTC, elizabeth-jimenez requested changes
1. in _variables.scss go through the 6 configs for Agenda Item Maintenance Legs and update, as needed.
2. in AgendaLeg.jsx update onHover$()

2024-02-27 15:32 UTC, cagbakwu commented
Had to update _agendaItemRow as well 👍

2024-02-27 17:46 UTC, elizabeth-jimenez commented
- [ ]  agenda item maintenance read
- [ ]  AIM edit
- [ ]  panel agenda item
- [ ]  print view of panel meeting agenda
- [ ]  agenda item history

2024-02-27 17:50 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/37dcb92f-bb27-4906-9a81-1d316dc3f432)
seems like a lot of space between Action and the top X row

2024-02-27 17:50 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/85f805cb-24c1-4282-9434-c4fb4c5e961c)
AIM Edit - not sure if this was already on dev branch tho, i can go verify in a bit

2024-02-27 17:53 UTC, elizabeth-jimenez commented on src/sass/_variables.scss
> +  "Action": 1,
Action shouldn't be 1 here, look at the rendered css (dev tools) to see why

2024-02-27 17:55 UTC, elizabeth-jimenez commented on src/sass/_variables.scss
>  $aim-legs-sm-height-config-read-only: (
try to understand how these are being used

2024-02-27 18:01 UTC, elizabeth-jimenez commented
![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/23065001/4a557b62-a963-4043-a9a8-bf0fd8cba2d5)
verified this is how it looks on dev branch

The only one that is messed up in dev is the Location/ Org, which is my bad, so you can go ahead and ignore that one; i'll open a PR for it shortly

2024-02-28 15:56 UTC, elizabeth-jimenez commented
looking at patrick's commit, you may need to also update the hover in src/Components/Agenda/AgendaLeg/AgendaLeg.jsx

2024-02-28 15:58 UTC, elizabeth-jimenez commented
since Action was moved to the top row, all of the variables in config need to be +1 - that should be all that's needed

2024-02-28 17:07 UTC, elizabeth-jimenez commented
Checking
- [ ]  Agenda Item Maintenance Read (changed)
- [ ]  Agenda Item Maintenance Edit (changed)
- [ ]  Agenda Item history
- [ ]  Panel Meeting Agenda items
- [ ]  Print View of Panel (added)

2024-02-28 18:25 UTC, merged