TM-5777, Merge Assignment Cycles
MetaPhase-Consulting/State-TalentMAP pull request #2924
Opened 2024-03-26 02:45 UTC by M00staff

Dual Merge: 
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/961)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/457)

[Ticket](https://metaphase.atlassian.net/browse/TM-5777)

2024-03-26 02:47 UTC, M00staff commented on src/Components/CycleManagement/AssignmentCycleEdit.jsx
> +          {(isSuperUser && !cycleClosed) &&
just hide the edit button altogether when a cycle is closed

2024-03-26 02:51 UTC, M00staff commented on src/Components/CycleManagement/AssignmentCycleEdit.jsx
> -              disabled={disableFields}
So, it turns out that in FSBID, you can change a cycle's status from Merge to anything else ... its just that in a "Merge" status, all the other fields are locked (until you change it to anything else) 🤷

Leaving in the rest of the disable logic - pretty much only "Closed" statuses are completely locked.

2024-03-26 02:53 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +  }, [cycleManagementMergeSuccess]);
on successful merge - you get taken to what was the "Target" cycle and are prompted to update the newly merged cycle's name in the toast. 

"Source" cycle will be closed.

2024-03-26 02:56 UTC, M00staff commented on src/Constants/SystemMessages.js
> +export const ASSIGNMENT_CYCLE_MERGE_SUCCESS = 'Cycles merged successfully - please rename the newly merged Cycle';
wording? 🤷

2024-03-27 05:21 UTC, jlam-mpc commented on src/Components/CycleManagement/AssignmentCycleEdit.jsx
> +  const cycleActive = assignmentCycleData?.cycle_status === 'A';
Nice way of organizing this to make the conditionals throughout this component more readable.

2024-03-27 12:00 UTC, elizabeth-jimenez commented on src/Components/CycleManagement/CycleManagement.jsx
> +                        {'Cycle Date Classifications'}
is this a placeholder for now?

2024-03-27 12:23 UTC, elizabeth-jimenez commented on src/Components/CycleManagement/MergeAssignmentCycles.jsx
> +  const cancel = () => swal.close();
```suggestion
    const cancel = (e) => {
        e.preventDefault();
        swal.close();
   };
```

2024-03-27 12:32 UTC, elizabeth-jimenez commented on src/Components/CycleManagement/MergeAssignmentCycles.jsx
> +          <span className="bs-validation-container">
can add a class in `_common.scss` for width 100% instead of using `bs-validation-container`

2024-03-27 12:34 UTC, elizabeth-jimenez requested changes
Looks great! Just two things:
- preventDefault for Cancel of Merge Cycles modal
- bs-validation-container class replacement

2024-03-27 14:10 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +                        {'Cycle Date Classifications'}
YES!

planning ahead lol

2024-03-27 14:17 UTC, M00staff commented on src/Components/CycleManagement/AssignmentCycleEdit.jsx
> +  const cycleActive = assignmentCycleData?.cycle_status === 'A';
thanks for noticing - I'm a big proponent of "readable over slick" 

... that being said - I'm often VERY tempted to shoot for super slick one liners, at the expense of confusing my future self, of course 😅

but, screw that guy - its HIS problem!

2024-03-27 14:19 UTC, M00staff commented on src/Components/CycleManagement/MergeAssignmentCycles.jsx
> +          <button onClick={mergeCycles} disabled={!disableSave}>Merge Cycles</button>
updated!

2024-03-27 14:27 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +                        {'Cycle Date Classifications'}
updated!

2024-03-27 14:27 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
> +                          {' Add New Assignment Cycle'}
no worries - its a quick fix ... added a common CSS class for it

2024-03-27 14:27 UTC, jlam-mpc commented on src/Components/CycleManagement/CycleManagement.jsx
>                      {isSuperUser &&
Use this suggestion if you need to retain the split user/permission conditionals for each link.
```suggestion
                <div className="cm-heading">
                  <div className="cm-classifications">
                    {isSuperUser &&
                      <Link
                        onClick={(e) => {
                          e.preventDefault();
                          createNewAssignmentCycle();
                        }}
                        to="#"
                      >
                        Cycle Date Classifications
                      </Link>
                    }
                  </div>
                  <div className="cm-new-merge">
                    {!isSuperUser &&
                      <Link
                        onClick={(e) => {
                          e.preventDefault();
                          createNewAssignmentCycle();
                        }}
                        to="#"
                      >
                        <FA className="fa-solid fa-plus" />
                        Add New Assignment Cycle
                      </Link>
                    }
                    {isSuperUser &&
                      <Link
                        onClick={(e) => {
                          e.preventDefault();
                          mergeCycles();
                        }}
                        to="#"
                      >
                        <FA className="fa-solid fa-plus" />
                        Merge Assignment Cycles
                      </Link>
                    }
                  </div>
                </div>
```

2024-03-27 14:28 UTC, M00staff commented on src/Components/CycleManagement/MergeAssignmentCycles.jsx
> +  const cancel = () => swal.close();
whoops - yea i just changed this to add the prevent default - fixed now!

2024-03-27 14:32 UTC, M00staff commented on src/Components/CycleManagement/CycleManagement.jsx
>                      {isSuperUser &&
nice - thanks for posting the code to make it quicker!

2024-03-27 15:01 UTC, jlam-mpc approved these changes

2024-03-27 15:02 UTC, elizabeth-jimenez approved these changes
➕

2024-03-27 15:10 UTC, merged