TM-5672 update cycle date classifications
MetaPhase-Consulting/State-TalentMAP pull request #2950
Opened 2024-04-12 07:03 UTC by M00staff

Definitely go through this a bit carefully - flew through all of this in the middle of the night 🙃

Dual Merge: 
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/970)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/463)

[Ticket](https://metaphase.atlassian.net/browse/TM-5672)

2024-04-12 07:13 UTC, M00staff commented on src/Components/CycleManagement/CycleClassifications.jsx
> +  };
this was pretty gnarly - took most of it from Jeanie's Position Classifications code

might wanna throw some console logs in there to mess with it

2024-04-12 07:15 UTC, M00staff commented on src/Components/CycleManagement/CycleClassifications.jsx
> -  const cs = results?.classification_selections ?? [];
not ENTIRELY sure these values needed to be stored in state & updated with the useEffect 🤔 but could be missing something

2024-04-12 07:19 UTC, M00staff commented on src/Components/CycleManagement/CycleClassifications.jsx
> +                    </td>
i thought this was clever & it took a min to think through > when you click Edit for a cycle > throw that cycle's data into the local state > & render that cycle's checkboxes instead of the data in the return.

2024-04-12 07:20 UTC, M00staff commented on src/Components/CycleManagement/CycleClassifications.jsx
> +  );
check to make sure the Cycle in Edit is the one that should have a save/cancel button

2024-04-12 07:21 UTC, M00staff commented on src/sass/_positionSearch.scss
> +    accent-color: darkorange;
cleaned up the ui 😍

<img width="1911" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/34ded4e0-eb72-425d-971f-6aa211ac4d3d">

2024-04-12 07:24 UTC, M00staff commented on src/sass/_positionSearch.scss
> +}
need to double check - should we filter out some cycles?

i wanna say FSBID doesn't show ALL of them ... but, the endpoint returns everything without passing in if the cycle is closed 🤔

just added a scrollbar to account for it looks wise ... could be a follow on ticket - but, i dont think this feature is used much

2024-04-23 13:17 UTC, jlam-mpc requested changes
Logic looks good, AC met, everything works and reading through the integration work + spreadsheets seem to pass in my head.

I just left a couple of comments for you to look into for minor code cleanup, etc.

2024-04-23 13:17 UTC, jlam-mpc commented on src/sass/_positionSearch.scss
> +    accent-color: darkorange;
```suggestion
  .cm-cycle-classes-check{
    &.read-only {
      pointer-events: none;
      accent-color: darkorange !important;
    }
```

2024-04-23 13:17 UTC, jlam-mpc commented on src/sass/_positionSearch.scss
> +    accent-color: darkorange;
Looks much better and more visible. I do want to say that instead of declaring `darkorange`, we put a universal orange color in the same location $primary-blue is set so that every time we use orange we're using the same hexcodes. 

I also wanna say we should still distinguish the style of a disabled checkbox versus an editable one. I added a codeblock suggestion in case you wanted to try it.

2024-04-23 13:17 UTC, jlam-mpc commented on src/Components/CycleManagement/CycleClassifications.jsx
> +                    </td>
Looks good to me! I'd recommend pulling the line to check if the checkbox is checked (wow words) into a function so it can be reused and if it ever needs changing, it can be done in one place

```
const isChecked = (cycle) => {
  const foundCheck = cycle?.values?.find(value => c.code === value.code && value.value === '1');
  return foundCheck ?? false;
}
```

2024-04-23 13:17 UTC, jlam-mpc commented on src/Components/CycleManagement/CycleClassifications.jsx
>    const cycleClassCard = () => (isLoading ?
Wanted to suggest using this instead, which also adapts the styling suggestion I made below + pulls out your editable card check so that the logic is only called once:

```
  const cycleClassCard = () => (isLoading ?
    <div className="loading-animation--5">
      <div className="loading-message pbl-20">
        Loading additional data
      </div>
    </div> :
    (cycles?.map(cycle => {
      const editable = checkCycleToEdit(cycle.cycle_id, cycle.cycle_code);
      return (
        <div className="position-classifications cm-cycle-classes">
          <Row fluid className="position-content--subheader">
            <div className="line-separated-fields">
              <div>
                <span>{cycle?.cycle_name} - {cycle?.cycle_desc}</span>
              </div>
            </div>
            {(cycleToEdit === false && isSuperUser) &&
              <button
                className="toggle-edit-mode"
                onClick={() => setCycleToEdit({
                  id: cycle.cycle_id,
                  code: cycle.cycle_code,
                  values: cycle.values,
                })}
              >
                <FA name="pencil" />
                <div>Edit</div>
              </button>
            }
          </Row>
          <div className="table-container">
            <table>
              <thead>
                <tr>
                  {classifications?.map((o) => (
                    <th key={o.code}>{o.short_description}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                <tr>
                  {classifications?.map((c) => {
                    return (
                      <td key={c.code}>
                        <input
                          type="checkbox"
                          name={c.code}
                          className={`cm-cycle-classes-check ${editable ? '' : 'read-only'}`}
                          onChange={(event) => { if (editable) handleSelection(c.code, event) }}
                          readOnly={!editable}
                          checked={editable ?
                            (cycleToEdit?.values?.find(value => c.code === value.code && value.value === '1') ?? false) :
                            (cycle?.values?.find(value => c.code === value.code && value.value === '1') ?? false)
                          }
                        />
                      </td>
                    );
                  })}
                </tr>
              </tbody>
            </table>
          </div>
          {editable &&
            <div className="position-form--actions">
              <button onClick={() => setCycleToEdit(false)}>Cancel</button>
              <button onClick={handleSubmit}>Save</button>
            </div>
          }
        </div>
      )
    }))
  );
```

2024-04-23 13:17 UTC, jlam-mpc commented on src/Components/CycleManagement/CycleClassifications.jsx
> -  const cs = results?.classification_selections ?? [];
The reason why I did this was because after deploying, not sure if constants and states operate differently in production environments versus live/development ones but if you dereference the data with regular constants  like this:

```
  const classifications = results?.cycle_classifications;
  const cycles = results?.classification_selections;
```

The storage of these values sometimes don't update as the state of `results` changes. If your results value doesn't change or you re-render the component upon each save, this comment can be disregarded. But, also, I'm not sure if that was really the issue or if my issue lied elsewhere, I just do this sometimes to be safe. I say just keep this code, deploy, and test keeping these things in mind to see if you have that problem.

2024-04-23 16:22 UTC, M00staff commented on src/Components/CycleManagement/CycleClassifications.jsx
> -  const cs = results?.classification_selections ?? [];
yep!

- on a successful save - page reloads, so component will re-render with new results (also the selections are stored in a local state) 

also worth noting
- `not sure if constants and states operate differently in production environments` - so, this definitely shouldn't be different between environments 🤔

2024-04-23 17:40 UTC, M00staff commented on src/Components/CycleManagement/CycleClassifications.jsx
>    const cycleClassCard = () => (isLoading ?
so - this was a fun rabbit hole... 
```
className={`cm-cycle-classes-check ${editable ? '' : 'read-only'}`}`
```

^^ that line breaks the ESLint checking in the entire file, for some reason.

you'll get this error (only visible in the console) but also, the editor will stop showing red squiggles & the console will stop noticing any other Lint errors or warnings in the rest of the file. 

![image](https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/ff9942af-46b5-469f-867e-47f5f610e9c0)


I tinkered with it and wound up having to add this to the ESLintRC
```
    "template-curly-spacing" : "off",
    "indent": ["error", 2, { "ignoredNodes": ["JSXAttribute", "JSXSpreadAttribute", "TemplateLiteral"], "SwitchCase": 1 }],
```

... I believe this was happening in every file with that was using a template literal in the same kind of way 🤔

2024-04-23 17:50 UTC, M00staff commented on src/sass/_positionSearch.scss
> +    accent-color: darkorange;
FWIW - i dont think the important flag was needed here, so i dropped it

2024-04-23 18:02 UTC, M00staff commented
made all the updates - should be GTG

2024-04-23 20:51 UTC, jlam-mpc commented on src/Components/CycleManagement/CycleClassifications.jsx
>    const cycleClassCard = () => (isLoading ?
This explains so much...

2024-04-23 21:16 UTC, M00staff commented on src/Components/CycleManagement/CycleClassifications.jsx
> -  const cs = results?.classification_selections ?? [];
you know ... 🤔

that ESLint bug might explain why you were seeing weird behavior, here

2024-04-23 21:50 UTC, merged