TM-5848, Rework Bid Audit Ui
MetaPhase-Consulting/State-TalentMAP pull request #2956
Opened 2024-04-19 03:41 UTC by M00staff

Dual Merge: 
- [API PR](linkToAPIPR)
- [Mock PR](linkToMockPR)

[Ticket](https://metaphase.atlassian.net/browse/TM-5848)

Most the info is in the ticket - had to re-work the Ui for this page, mainly just moving the 'In-Category' and 'At-Grade' stuff to its own page ... a few other cleanup things - there will be another PR merging into this that continues the cleanup 

Prolly better to review when the other part is done

2024-04-22 14:59 UTC, M00staff commented on src/Components/AdministratorPage/AdministratorPage.jsx
> +        <Route path="/profile/administrator/bidaudit/" render={() => <BidAudit />} />
Per new designs - hitting 'At-Grade' or 'In-Category' will take you to a new page where you can update what Employee Grades and Categories are considered 'At-Grade' or 'In-Category' for the Cycle's Open Positions 

<img width="2084" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/863911c5-cac4-4da0-8b9a-8593f8cd8be2">

2024-04-22 15:06 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +                    }
<img width="409" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/6b6a457d-e9ab-4450-b81c-77182049d72c">

2024-04-22 15:12 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAuditCategory.jsx
> +  // const [bidAuditData$, setBidAuditData$] = useState(bidAuditData);
this is the Ui only - with fake data. 

i got uber carried away on Friday and didn't realize i had already made tickets for all of this work 

https://metaphase.atlassian.net/browse/TM-5916

2024-04-22 15:16 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAuditGrade.jsx
> +            {/* these disabled dropdowns probably dont need to be dropdowns will fix in next PR */}
i remembered, for once

<img width="527" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/8c867c58-87ef-4ba9-9750-a5cf0241c972">

https://metaphase.atlassian.net/browse/TM-5910

2024-04-22 15:24 UTC, M00staff commented on src/actions/bidAudit.js
> +// ================ Bid Audit GET In Category/At Grade ================
This action will be for the In-Category/At-Grade GET request ... pretty sure i can just use the same action for both

2024-04-22 15:26 UTC, M00staff commented on src/reducers/bidAudit/bidAudit.js
> +// ================================================================ // Below not integrated/used yet
anything above this line is used - below unused ... hopefully this will be a better way of keeping track of what can get blown away (i think i might have missed a few with Assignment Cycles 😕)

2024-04-22 15:26 UTC, M00staff commented on src/actions/bidAudit.js
> +// ================================================================ // Below not integrated/used yet
anything above this line is used - below unused

2024-04-22 15:27 UTC, M00staff commented on src/reducers/bidAudit/bidAudit.js
> +export function bidAuditLoading(state = false, action) {
technically just renamed these ... can prolly blow them away now, but kept them here for some reason 🤔

i think i was just fried, tbh

2024-04-23 23:16 UTC, jlam-mpc requested changes

2024-04-23 23:16 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +    bidAuditFetchLoading ? <Spinner type="bureau-filters" size="small" /> :
Want to suggest using getOverlay() at the top level here because if the main list doesn't load, there is an issue getting even the filters. I know in other components (e.g. Projected Vacancy) there is a separate spinner at the root div and then getOverlay is used in the results section but for your component, the filters are dependent on the filters...

2024-04-23 23:16 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +    bidAuditFetchLoading ? <Spinner type="bureau-filters" size="small" /> :
I take that back you can ignore this comment. Not super important and a little nit picky. I think it's fine to leave it as long as the page doesn't break and an error message is still displayed when `bidAuditFetchLoading` is true.

2024-04-23 23:16 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +                'Filters and Pagination are disabled if any cards are in Edit Mode.',
```suggestion
                'Filters are disabled if any cards are in Edit Mode.',
```

2024-04-23 23:16 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
> +      { 'Category': cycle_category || 'None listed' },
For any instance of hardcoded 'None listed' I would use `DEFAULT_TEXT` or `NO_VALUE` from `SystemMessages.js`

2024-04-23 23:16 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
> +    history.push(`/profile/administrator/bidaudit/grade/${cycle_id}/${audit_id}/`);
onInCategory and onAtGrade could be the same function if you so desire

```
  const onOptionClick = (type) => {
    history.push(`/profile/administrator/bidaudit/${type}/${cycle_id}/${audit_id}/`);
  };
```

and just call like:

```
          <div className="ba-flex-end">
            <button onClick={() => onOptionClick(category)}>View In Categories</button>
            <button onClick={() => onOptionClick(grade)}>View At Grades</button>
          </div>
```

I'm always vouching for reducing common code lines where possible and IF it is sensible- I think it works here

2024-04-23 23:16 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
> +            <button onClick={onAtGrade}>View At Grades</button>
See recommendation listed earlier in this file

2024-04-23 23:16 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAuditCategory.jsx
> +export default withRouter(BidAuditCategory);
Functionality wise, looks good to me, thus demoable. Code poses no risks to other components and since I suspect this and BidAuditGrade will be heavily adapted once integration is worked on, I don't want to grind my gears too much nitpicking at this code. Let's just merge it in since the UI works and I can rereview for code integrity when it gets to it's final form during integration.

2024-04-23 23:17 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +                    }
I'll look into this a bit more tomorrow. If anything, we could push a hotfix while the bulk of these tickets get tested. I'm not ignoring this comment though, very insightful. Just wanted to expedite the process of any of your 3 tickets getting tested.

2024-04-23 23:32 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +                    }
yea - also, dunno if i mentioned ... one way or another this WILL get resolved 

There are still tickets for the Edit or GET of the In-Category/At-Grade stuff ... so, this has NOTHING to do with the current ticket/work (the page just shows Ui) and nothing is actually editable

2024-04-23 23:46 UTC, jlam-mpc approved these changes

2024-04-23 23:58 UTC, merged