TM-5876, Create New Bid Audit
MetaPhase-Consulting/State-TalentMAP pull request #2968
Opened 2024-05-02 02:05 UTC by M00staff

Dual Merge: 
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/982)

[Ticket](https://metaphase.atlassian.net/browse/TM-5876)

2024-05-02 02:12 UTC, M00staff commented on src/sass/_bidAudit.scss
> -  }
was hoping to avoid getting lost in CSS for as much of the integration work as possible - but couldn't help it with this (it took A WHILE to clean this file up, and I'm not sure i got everything)

also, i had been so worried about missing and/or not dropping unused Actions & Reducers (like i think i did with some of the Assignment Cycles stuff) that i COMPLETELY spaced on who knows how much unused CSS we have in some of these components that we build out for the 9/30 crunch. 

... i dont think there's much we can do about it now, outside of cleaning it up when the opportunity arises - but its a HUGE time suck

2024-05-02 02:15 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +  }, [bidAuditCycles]);
had to jimmy this up in a kind of weird way so it doesn't render the modal until the call to get the list of cycles completes & also just so it doesn't randomly pop up added the `setNewAuditClicked` state 🤔 ... there might have been a better/slicker way to do this, but its what i came up with 🤷

... prolly could have just made the call on the Main Bid Audit page load 🤔

2024-05-02 02:17 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +  };
this was just renamed - turns out "running" a bid audit and updating the bid counts are two separate things 🤷

2024-05-06 04:52 UTC, jlam-mpc requested changes

2024-05-06 04:52 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +  }, [bidAuditCycles]);
I'd want to recommend removing a create clicked state and just directly calling the function to open the the sweetalert.

To be specific, my recommendation is to

1. Remove this effect hook
3. Add an error state to your action/reducer for the active cycles list
4. Add a prop for the error and loading values
5. Conditionally show that Alert error message inside of the modal
6. Show a loading spinner in the modal if the data is still loading
7. Handle the swal like so:

```
  const showCreateModal = () => {
    swal({
      title: 'Create New Audit Cycle',
      button: false,
      content: (
        <BidAuditModal
          cycleOptions={bidAuditCycles}
          cycleOptionsLoading={bidAuditFetchCyclesLoading}
          cycleOptionsErrored={bidAuditFetchCyclesErrored}
          onSubmit={onSubmit}
        />
      ),
    });
  };
```


```
  const onCreateNewAuditClick = (e) => {
    e.preventDefault();
    dispatch(bidAuditFetchCycles());
    showCreateModal();
  };
```

2024-05-06 04:52 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +  const bidAuditCycles = useSelector(state => state.bidAuditCycles);
Unfortunate that you can't call these inside of swal for the BidAuditModal component because of a lack of a provider wrapper. Scott actually made a ReactModal component to handle situations like this but I don't want you to rabbithole into that for this PR last minute. I do want to say, in the future, you should use ReactModal to handle any modals that aren't simple alert messages, because this component allows you to do more complex things and use hooks in it, call data, etc.

2024-05-06 04:52 UTC, jlam-mpc commented on src/sass/_bidAudit.scss
>  }
It was quick for me to play with and do but I wanted to recommend this because it looks a little more readable to me:
<img width="693" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/121953273/88483abc-0e39-4be9-8574-433d4da24f74">


```
$bid-audit-input-width: 460px;

.bid-audit-form-modal {
  .filter-div-modal {
    padding: 10px;

    .label {
      text-align: left;
    }
  }
}

.bid-audit-modal-wrapper {
  width: 100%;
  height: 300px;

  .ba-modal-div {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    padding-top: 5px;

    >div:first-child {
      width: 160px;
      text-align: end;
      padding-right: 15px;
    }

    .react-datepicker__input-container {
      display: flex;
      justify-content: end;

      input {
        text-align: left;
        width: $bid-audit-input-width;
        height: 44px;
        padding-left: 40px;
      }
    }
  }

  .date-picker-validation-container {
    position: relative;

    .fa-calendar {
      position: absolute;
      left: 15px;
      top: 18px;
      color: gray;
      z-index: 1;
    }

    .fa-close {
      position: absolute;
      right: 10px;
      top: 18px;
      color: gray;
      z-index: 1;
    }
  }

  .bid-audit-modal-word-count,
  .bid-audit-modal-number {
    display: flex;
    width: $bid-audit-input-width;
  }

  .bid-audit-modal-word-count {
    justify-content: flex-end;
    font-size: 14px;
    margin-bottom: -16px;
  }

  .bid-audit-modal-description-text {
    text-align: center;
    height: 44px;
  }

  .bid-audit-modal-buttons {
    margin-top: 35px;
  }
}
```

and then just change these in the modal return

```
<div className="ba-modal-div">
  <div>Audit Number:</div>
  <span className="bid-audit-modal-number">{assignmentCycle?.audit_number + 1 || '--'}</span>
</div>
```

```
<div className="ba-modal-div">
  <div>Audit Description:</div>
  <div>
    <input
      type="text"
      maxLength="100"
      autoComplete="off"
      name="description"
      className="bid-audit-modal-input"
      onChange={(e) => setAuditDescription(e.target.value)}
    />
    <div className="bid-audit-modal-word-count">
      {auditDescription?.length} / 100
    </div>
  </div>
</div>
```

2024-05-07 01:37 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> +  }, [bidAuditCycles]);
Nice - thank you!!

Not sure why i couldn't get this to work ... maybe because i was dispatching the action in the same function the opened the sweet alert? 🤔

I just kept getting the modal with no data 🤷

2024-05-07 01:40 UTC, M00staff commented on src/actions/bidAudit.js
> +      }, {
a result of derp & copy/pasting, i suspect .. will have to get rid of all the `(jwt, request.data)`'s and `data = request.get('data')` bits in the API for all these calls... 

BUT - i'll totally retroactively take care of them all/clean this all up in the next round of Bid Audit work

2024-05-07 01:41 UTC, M00staff commented on src/sass/_bidAudit.scss
>  }
🙌⭐️

2024-05-07 01:43 UTC, M00staff commented
good stuff @jlam-mpc - all set!

2024-05-07 15:38 UTC, merged