TM-6076: Publishable Positions Re-Integration (Read, Filtering, Pagination)
MetaPhase-Consulting/State-TalentMAP pull request #2991
Opened 2024-05-22 18:48 UTC by pveland621

WIP while standing up PRs

ACs:
- Publishable Position Cards reading in all relevant fields
- Filters loading + filter requests look good
- Pagination/Total Results works as best we can test on local

Triple Merge: 
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/999)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/476)

[Ticket](https://metaphase.atlassian.net/browse/TM-6076)

2024-05-28 12:03 UTC, jlam-mpc requested changes

2024-05-28 12:03 UTC, jlam-mpc commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +      { 'Publishable Status': data?.psCD || DEFAULT_TEXT },
I left a comment about fixing up the list return JSON. We should probably return all of the data in case and also make sure to standardize how to take care of fields that have both a code and desc if where we might need to use either or (desc in read only, code in edit mode).

2024-05-28 12:03 UTC, jlam-mpc commented on src/Components/PublishablePositions/PublishablePositions.jsx
> +  const data$ = data?.results;
Worried there may be issues with this in prod but I think we just need to deploy and test to find out. Sometimes we need to wrap this in an effect hook to take care of the data$ pointer changing.

2024-05-28 12:03 UTC, jlam-mpc commented on src/Components/PublishablePositions/PublishablePositions.jsx
> +            </div>
Now that we have pagination I wonder if we even need the filters requirement (user must select at least 2 filters). I would check with Scott Elizabeth or Tim to see if there was any exclusive requirement for that or if it was just a round about solution to no pagination and timeouts from heavy payloads. If it's not longer needed, we can remove it in this PR. The user could then load up the page and instantly see 10 results with no filter on it

2024-05-29 13:57 UTC, pveland621 commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +      { 'Publishable Status': data?.psCD || DEFAULT_TEXT },
deja vu but i always forget the protocol - i know there's either "only return the fields you need" and "return everything in case we need it later" but i can't remember which one we decide on 🤔

2024-05-29 13:59 UTC, pveland621 commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +      { 'Publishable Status': data?.psCD || DEFAULT_TEXT },
> Shouldn't this be from the `posstatusdesc` field in the FSBID return? It's also not being returned in your backend.

double checking but there are two 'statuses' returned in this payload, one is the position status and one is the publishable status - i believe we want the publishable status here, correct?

2024-05-29 20:42 UTC, elizabeth-jimenez commented on src/Components/PublishablePositions/PublishablePositions.jsx
> +            </div>
I think it was indeed "just a round about solution to no pagination and timeouts from heavy payloads", but i have seen fsbid require multiple filters too in some places - again maybe they too did it bc of a lack of pagination, but defs something we can ask Tim to dbl check in dev1 fsbid for Publishable Ps

2024-05-30 12:47 UTC, pveland621 commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +      { 'Publishable Status': data?.psCD || DEFAULT_TEXT },
@elizabeth-jimenez i have no problem doing that but this payload is about 63 fields long, are we saying to map every field? again no problem, it just seems like a lot

2024-05-30 12:48 UTC, pveland621 commented on src/Components/PublishablePositions/PublishablePositions.jsx
> +            </div>
double checking with Tim today

2024-05-31 01:33 UTC, jlam-mpc commented on src/Components/PublishablePositionCard/PublishablePositionCard.jsx
> +      { 'Publishable Status': data?.psCD || DEFAULT_TEXT },
Patrick, in my PV work I just returned the payload verbatim because I don't see the value translating it back and forth betwen FSBID => TM and them TM => FSBID during edits. I wanted to bring this up to other devs to see if we can make it a standard. The HRTMapData/WS work names them a little silly but for FSBID field names I'm honestly okay with just matching it all 1-to-1 to reduce complexity and confusion.

2024-05-31 01:33 UTC, jlam-mpc commented on src/Components/PublishablePositions/PublishablePositions.jsx
> +            </div>
Okay sound good!

2024-06-03 14:54 UTC, elizabeth-jimenez commented on src/Components/PublishablePositions/PublishablePositions.jsx
> +            </div>
sorry, i didnt realize this until right now - just bc fsbid requires it, doesnt mean the EP does; cause it could be that it is enforced just at the FE, like how we did here. I hit the EP with no filters and it worked, so we dont need to require 2 anymore

2024-06-03 17:03 UTC, jlam-mpc commented on src/Components/PublishablePositions/PublishablePositions.jsx
> +            </div>
Should we just keep it for now?

2024-06-03 17:18 UTC, jlam-mpc approved these changes

2024-06-05 12:53 UTC, merged