TM-6048, Run Bid Audit
MetaPhase-Consulting/State-TalentMAP pull request #2994
Opened 2024-05-25 01:46 UTC by M00staff

Dual Merge: 
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/1001)
- [Mock PR](https://github.com/MetaPhase-Consulting/mock-fsbid/pull/477)

[Ticket](https://metaphase.atlassian.net/browse/TM-6048)

2024-05-25 01:52 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAudit.jsx
> -                  Create New Audit Cycle
cleared up wording here, and a few other places

2024-05-25 01:55 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
> +      { 'Audit Date': audit_date || showRunBidAudit() },
if no date, show the run button - running the audit should refresh the page & today's date will be here ... still need to double check if there are any other stipulations (for example - can you still run an audit, if the cycle is closed)

also, seems like there's a bug with this proc (or some business logic I don't see) - will have a WS blocker for this

2024-05-25 01:57 UTC, M00staff commented on src/actions/bidAudit.js
> -      }, {
both these guys wind up hitting the `create_new_audit_req_mapping`  call from this guy

<img width="544" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/6227a884-f64c-4124-9ba0-2ca9ccf1bd8a">

2024-06-03 20:06 UTC, jlam-mpc requested changes

2024-06-03 20:06 UTC, jlam-mpc commented on src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
> +          <button onClick={() => swal.close()}>Cancel</button>
Anytime you have both a submit and cancel button next to each other I would keep in mind to differentiate the styling so that we prevent the accidental user clicks on submit vs cancel

```suggestion
          <button className="usa-button-secondary" onClick={() => swal.close()}>Cancel</button>
```

2024-06-04 00:22 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
> +      { 'Audit Date': audit_date || showRunBidAudit() },
yea - i got the deets and added to a follow up ticket

Essentially, the cycle needs to have Open Positions & those Positions have to have been Posted

https://metaphase.atlassian.net/browse/TM-6169

2024-06-04 00:26 UTC, M00staff commented on src/Components/AdministratorPage/bidAudit/BidAuditCard.jsx
> +      { 'Audit Date': audit_date || showRunBidAudit() },
its pretty generic - i figure adding a note to the modal that pops up when you click the Run button ... MAYBE something in the API 🤔

<img width="1048" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/957f5087-8992-4f4c-8dcf-5ffbbf6b446c">

2024-06-04 13:38 UTC, jlam-mpc approved these changes

2024-06-04 13:47 UTC, merged