TM-5497-AIM-Remarks
MetaPhase-Consulting/State-TalentMAP pull request #2998
Opened 2024-06-03 00:34 UTC by cagbakwu

[Ticket](https://metaphase.atlassian.net/browse/TM-5497)

2024-06-03 00:35 UTC, cagbakwu commented on src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
> +      if (Object.keys(remark$).length !== 0) {
If the potential remarks are empty, it just returns the original set remarks if any.

2024-06-04 01:32 UTC, M00staff requested changes
I might be off here - but, I cannot recreate the issue from the ticket

It looks to me like text needs to be entered in order for the user to be able to save a remark?

<img width="427" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/950d6d6c-dedd-4ce6-b99b-5df0c300dc4b">

It would be nice if the ticket had some kind of steps to be able to reproduce - but, also it looks like the ticket was created in January ... could it be that this was already solved?

2024-06-04 01:41 UTC, M00staff commented on src/Components/Agenda/AgendaItemMaintenanceContainer/AgendaItemMaintenanceContainer.jsx
> +      if (Object.keys(remark$).length !== 0) {
I'm not sure what this is even doing ... if you `console.log(Object.keys(remark$));` this is what you get, for any added remark. 

<img width="221" alt="image" src="https://github.com/MetaPhase-Consulting/State-TalentMAP/assets/12723877/992ba45d-d896-4ec4-9cdd-4cccc9986d0f">

it doesn't have anything to do with the remark insert

2024-06-04 01:43 UTC, M00staff commented
yea - it looks to me like this issue was solved by this PR, about 3 months ago

https://github.com/MetaPhase-Consulting/State-TalentMAP/pull/2868

ticket - https://metaphase.atlassian.net/browse/TM-5556 

... did you even check to see if this was an issue before trying to solve it?

Unless, I'm missing something?

2024-06-04 21:39 UTC, cagbakwu commented
@cagbakwu yea the text had to be entered for the save to become available but I was just adding a second check if somehow the app still allowed a save without it. It should never get to this so I could just close this one out.

2024-06-04 21:46 UTC, cagbakwu commented
@M00staff I did see that it wouldn't save without the text but I added a second check just in case the app bypassed the check. I didn't realize the creation date of this task until now. Ill close this one out.

2024-06-04 21:47 UTC, closed without merging