[TM-6358] TM1 Memo - Preview Card
MetaPhase-Consulting/State-TalentMAP pull request #3075
Opened 2024-08-09 00:29 UTC by jlam-mpc

[Ticket](https://metaphase.atlassian.net/browse/TM-6358)

2024-08-12 15:22 UTC, fimbriano requested changes
Should be good to go after the little things :)

2024-08-12 15:22 UTC, fimbriano commented on src/Components/TabbedCard/TabbedCard.jsx
> +      {existingTabs?.find(tab => activeTab == tab.value)?.content}
```suggestion
      {existingTabs?.find(tab => activeTab === tab.value)?.content}
```
co-pilot suggested fix to remove the eslint line above

2024-08-12 15:22 UTC, fimbriano commented on src/Components/TabbedCard/TabbedCard.jsx
>        {/* eslint-disable eqeqeq */}
```suggestion
```
i like to try to avoid using eslint-disable

2024-08-12 15:22 UTC, fimbriano commented on src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
> +      }, memo ? null : {
When you're in edit mode, the tabs show "Edit Notification", should each tab show "Edit Memo"?

2024-08-13 13:33 UTC, jlam-mpc commented on src/Components/AssignmentsSeparations/NotificationCard/NotificationCard.jsx
> +      }, memo ? null : {
Yes this is a good point but I intentionally left this change as well as many others alone for now since it'll be handled in a future ticket related to Memo Edit Mode!

2024-08-13 13:41 UTC, fimbriano approved these changes
👍

2024-08-13 15:42 UTC, merged