TM-4844-CDO-UI
MetaPhase-Consulting/State-TalentMAP pull request #3077
Opened 2024-08-12 19:25 UTC by cagbakwu

Dual Merge: 
- [API PR](linkToAPIPR)

[Ticket](https://metaphase.atlassian.net/browse/TM-4844)

2024-08-12 19:30 UTC, cagbakwu commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
>  import { Link } from 'react-router-dom';
Make sure your flag is enabled for CDO30 to see the dropdowns for cusp and eligible bidders for BidderPortfolioStatCard and BidderPortfolioStatRow

2024-08-13 20:55 UTC, jlam-mpc requested changes
Looks good to me, I revisited the API and made a note, and just a minor request for code cleanup.

2024-08-13 20:55 UTC, jlam-mpc commented on src/Components/BidderPortfolio/BidderPortfolioStatCard/BidderPortfolioStatCard.jsx
>      // Nothing to do yet, will add later
If this comment doesn't apply anymore you should remove it

2024-08-14 13:28 UTC, jlam-mpc approved these changes

2024-08-14 19:45 UTC, merged