TM-6509-CDO-Dropdown-UI
MetaPhase-Consulting/State-TalentMAP pull request #3095
Opened 2024-09-04 12:46 UTC by cagbakwu

Dual Merge: 
- [API PR](https://github.com/MetaPhase-Consulting/State-TalentMAP-API/pull/1074)

[Ticket](https://metaphase.atlassian.net/browse/TM-6509)

2024-09-04 15:49 UTC, fimbriano requested changes

2024-09-04 19:36 UTC, cagbakwu commented on src/actions/bidderPortfolio.js
>          dispatch(bidderPortfolioIsLoading(false));
@fimbriano this should stay true because this catch is when it actually errors out.

2024-09-05 01:07 UTC, cagbakwu commented on src/actions/bidderPortfolio.js
>            dispatch(bidderPortfolioIsLoading(false));
Good catch!

2024-09-05 01:07 UTC, cagbakwu commented on src/actions/bidderPortfolio.js
>          dispatch(bidderPortfolioIsLoading(false));
Good catch here too!

2024-09-05 18:39 UTC, RamelHenderson submitted a review, later dismissed

2024-09-05 20:36 UTC, fimbriano commented
Waiting to test in dev1 before merging

2024-09-10 22:08 UTC, jlam-mpc approved these changes
Going to approve to allow testers to test in the morning, looks like it achieves what it needs to locally and in dev1

Just a pointer that as you develop features on this page there seems to be a lot of console warnings that may or may not have to do with components you're adapting for a ticket so if it looks like a quick fix I would try to resolve these errors as you go (even if you didn't cause it whatsoever haha)

2024-09-12 15:34 UTC, merged