Tm 6597 edit cdo
MetaPhase-Consulting/State-TalentMAP pull request #3154
Opened 2024-11-26 19:43 UTC by RamelHenderson

2024-11-27 00:08 UTC, fimbriano requested changes

2024-11-27 00:08 UTC, fimbriano commented on src/Components/BidderPortfolio/BidderPortfolioContainer/BidderPortfolioContainer.jsx
> +    console.log('bidderPortfolio BidConatiner', bidderPortfolio);
remove logs
```suggestion
```

2024-11-27 00:08 UTC, fimbriano commented on src/Constants/Sort.js
> +// import { checkFlag } from 'flags';
```suggestion
import { checkFlag } from 'flags';
```

2024-11-27 00:08 UTC, fimbriano commented on src/Constants/Sort.js
> +const showCDOD30 = true;
add FF back
```suggestion
const showCDOD30 = checkFlag('flags.CDOD30');
```

2024-11-27 00:08 UTC, fimbriano commented on src/Containers/BidderPortfolio/BidderPortfolio.jsx
> +    console.log('bidderPortfolio BidPortfolio', bidderPortfolio);
remove logs
```suggestion
```

2024-11-27 00:08 UTC, fimbriano commented on src/actions/bidderPortfolio.js
> +    // }
whats happening with the season here?

2024-11-27 00:08 UTC, fimbriano commented on src/actions/bidderPortfolio.js
> +          console.log('BPSFD', data);
remove log
```suggestion
```

2024-11-27 00:13 UTC, RamelHenderson commented on src/actions/bidderPortfolio.js
> +    // }
I don't know much because this was Charles's work 😮‍💨

2024-11-27 00:15 UTC, fimbriano commented on src/actions/bidderPortfolio.js
> +    // }
hmm should we find out if this is needed then? lol

2024-12-02 14:53 UTC, fimbriano commented on src/Components/BidderPortfolio/BidControls/BidControls.jsx
> +          {/* } */}
```suggestion
          { showCDOD30 && 
          <div className="jc-toggle-container">
            <ToggleButton
              labelTextRight={!isCDOD30 ? 'Toggle CDO D3.0 View' : 'Toggle Client Search View'}
              onChange={this.onCDOToggleChange}
              checked={isCDOD30}
              onColor="#0071BC"
            />
          </div>
         }
```

2024-12-02 15:34 UTC, fimbriano approved these changes

2024-12-03 16:08 UTC, merged